<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="baidu-site-verification" content="X9D1pPcZDx" />
    <?php echo $this->headTitle()->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!--         Le styles-->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo.ico'))
        ->prependStylesheet($this->basePath('css/cn_main.css?20171225'));?>

    <!--         Scripts-->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

</head>
<body style="position: relative" data-spy="scroll" data-target="#about-navbar">

<div class="header" id="header-bg">
    <div class="head">
        <h1 class="logo"><a href="./" title="Ravision"><img src="<?php echo $this->basePath('img/common/logo_white.png')?>"  class="png" alt="Rayvision"></a></h1>
       <ul id="about-navbar"  class="nav nav-tabs" role="tablist">
           <li><a href="#about-intro">关于瑞云</a></li>
           <li><a href="#about-aptitude">瑞云资质</a></li>
           <li><a href="#about-develop">发展历程</a></li>
           <li><a href="#about-join">加入瑞云</a></li>
           <li><a href="#about-ability">技术能力</a></li>
           <li><a href="#about-bottom">联系我们</a></li>
       </ul>
        <ul class="nav_list">
            <li class="nav_li">
                <a href="javascript:void('0')" class="btn_nav" id="nav_more"><span class="ic_more more_img"></span><span class="more-text">更多</span></a>
                <div class="more_nav" id="more_nav">
                    <!--[if lt IE 9]>
                    <span class="opc_bg"></span>
                    <![endif]-->
                    <i class="ic_bdot" id="h_bdot"></i>
                    <ul id="h_nav">
                        <li>
                            <a href="<?php echo $this->url('home'); ?>" class="btn_snav">首页</a>
                        </li>
                        <li>
                            <a  href="<?php echo $this->url('case'); ?>" class="btn_snav">客户案例</a>
                        </li>
<!--                        <li>-->
<!--                            <a  href="--><?php //echo $this->url('join-us'); ?><!--" class="btn_snav">加入瑞云</a>-->
<!--                        </li>-->
                        <li>
                            <a  href="<?php echo $this->url('about'); ?>" class="btn_snav">关于瑞云</a>
                        </li>
                        <li>
                            <a  href="<?php if($_SERVER['REQUEST_URI'] ==="/"){echo "/en";}else{ echo "/en".$_SERVER['REQUEST_URI'];};?>" class="btn_snav hide-english">English</a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="En_btn"><span class="nav_line"></span> <a href="<?php if($_SERVER['REQUEST_URI'] ==="/"){echo "/en";}else{ echo "/en".$_SERVER['REQUEST_URI'];};?>" class="btn_nav">English</a></li>
        </ul>
    </div>
</div>
<div class="content">
    <!--禁止横屏的弹框-->
    <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel"  id="sp" data-backdrop="static"
         style="top: 0%!important; z-index: 9999;background-color: #000000;">
        <div class="modal-dialog modal-lg" role="document" style="width: 100%;height: 100%"  >
            <div class="modal-content" style="height: 100px;text-align: center;line-height: 100px;font-size: 20px;background-color: #000!important;
         color: #ffffff;width: 100%;height: 100%;position: relative" >
                <div style="width:500px; height:100px;position:absolute;top:50%;left:50%;margin:-50px 0 0 -250px;">
                    <img src="<?php echo $this->basePath('img/screen.png')?>" style="display: inline-block; margin-right: 20px">
                    竖屏享受最佳浏览效果！
                </div>
            </div>
        </div>
    </div>
    <script>
        window.addEventListener("onorientationchange" in window ? "orientationchange" : "resize", function() {
            if (window.orientation === 180 || window.orientation === 0) {
                $('#sp').modal('hide');
            }
            if (window.orientation === 90 || window.orientation === -90 ){
                $('#sp').modal({
                    show: true
                });
            }
        }, false);
    </script>
    <?php echo $this->content; ?>
</div> <!-- /container -->
<footer>
    <div class="container foot">
        <div class="row">
            <div class="col-md-3 col-sm-3 col-xs-12"></div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="row font-talk" style="padding: 0 50px">
                    <div class="col-md-3 col-sm-3 col-xs-3">
                        <div class="wechatq">
                            <img src="<?php echo $this->basePath('img/common/wechat_q.png')?>">
                        </div>
                        <a href="javascript:void(0)" class="wechat"></a>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-3">
                        <a href="http://www.weibo.com/renderbus" class="weibo" target="_blank"></a>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-3">
                        <a href="https://www.facebook.com/rayvision.inc" class="facebook" target="_blank"></a>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-3">
                        <a href="http://www.linkedin.com/company/rayvision" class="linkedin" target="_blank"></a>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12"></div>
        </div>
        <div class="row bottom-link">
            <div class="col-md-3 col-sm-3 col-xs-12"></div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <ul>
                    <li><a href="<?php echo $this->url('about'); ?>">关于瑞云</a> <span class="link-line"></span></li>
                    <li><a href="http://www.renderbus.com/news/main" target="_blank">新闻中心</a><span class="link-line"></span></li>
                    <li><a href="<?php echo $this->url('case'); ?>">成功案例</a><span class="link-line"></span></li>
                    <li><a href="http://www.rayvision.com/about.html#about-bottom">联系我们</a><span class="link-line"></span></li>
                    <li><a href="<?php echo $this->url('join-us'); ?>">加入瑞云</a></li>
                </ul>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12"></div>
        </div>
        <p class="recording">
            © 2017 深圳市瑞云科技有限公司 粤ICP备12028569号-2
        </p>
    </div>
</footer>

<script>
    var _hmt = _hmt || [];
    (function() {
        var hm = document.createElement("script");
        hm.src = "https://hm.baidu.com/hm.js?47a168644f86443bdb5c1ceca44e1e61";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
    })();
</script>

<?php
$this->inlineScript()->appendFile($this->basePath('js/pages/layout.js'));
?>
<?php echo $this->inlineScript() ?>
</body>
</html>
