<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle()->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

<!--         Le styles-->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo.ico'))
                        ->prependStylesheet($this->basePath('css/en_main.css'));?>

<!--         Scripts-->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
<!--        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">-->
<!--            <div class="container">-->
<!--            -->
<!--            </div>-->
<!--        </nav>-->
<div class="header">
    <div class="head">
        <h1 class="logo"><a href="./" title="Ravision"><img src="<?php echo $this->basePath('img/common/logo_white.png')?>"  class="png" alt="Rayvision"></a></h1>
        <ul class="nav_list">
            <li class="nav_li">
                <a href="#" class="btn_nav" id="nav_more"><span class="ic_more more_img"></span><span class="more-text">More</span></a>
                <div class="more_nav" id="more_nav">
                    <!--[if lt IE 9]>
                    <span class="opc_bg"></span>
                    <![endif]-->
                    <i class="ic_bdot" id="h_bdot"></i>
                    <ul id="h_nav">
                        <li>
                            <a target="_blank" href="<?php echo $this->url('en'); ?>" class="btn_snav">Home</a>
                        </li>
                        <li>
                            <a target="_blank" href="<?php echo $this->url('en-case'); ?>" class="btn_snav">Projects</a>
                        </li>
                        <li>
                            <a target="_blank" href="<?php echo $this->url('en-about'); ?>" class="btn_snav">About</a>
                        </li>
                        <li>
                            <a target="_blank" href="<?php echo $this->url('home'); ?>" class="btn_snav hide-english">中文</a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="En_btn"><span class="nav_line"></span> <a href="<?php echo $this->url('home'); ?>" class="btn_nav">中文</a></li>
        </ul>
    </div>
</div>
        <div class="content">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
<?php
$this->inlineScript()->appendFile($this->basePath('js/pages/layout.js'));
?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
