<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle()->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!--         Le styles-->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo.ico'))
        ->prependStylesheet($this->basePath('css/en_main.css?20171112'));?>

    <!--         Scripts-->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

</head>
<body style="position: relative" data-spy="scroll" data-target="#about-navbar">
<!--        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">-->
<!--            <div class="container">-->
<!--            -->
<!--            </div>-->
<!--        </nav>-->
<div class="header" id="header-bg">
    <div class="head">
        <h1 class="logo"><a href="./" title="Ravision"><img src="<?php echo $this->basePath('img/common/logo_white.png')?>"  class="png" alt="Rayvision"></a></h1>
       <ul id="about-navbar"  class="nav nav-tabs" role="tablist">
           <li><a href="#about-intro">About</a></li>
           <li><a href="#about-aptitude">qualifications</a></li>
           <li><a href="#about-develop">Milestones</a></li>
           <li><a href="#about-join">Milestones</a></li>
           <li><a href="#about-ability">Technology</a></li>
           <li><a href="#about-bottom">Contact</a></li>
       </ul>
        <ul class="nav_list">
            <li class="nav_li">
                <a href="#" class="btn_nav" id="nav_more"><span class="ic_more more_img"></span><span class="more-text">More</span></a>
                <div class="more_nav" id="more_nav">
                    <!--[if lt IE 9]>
                    <span class="opc_bg"></span>
                    <![endif]-->
                    <i class="ic_bdot" id="h_bdot"></i>
                    <ul id="h_nav">
                        <li>
                            <a target="_blank" href="<?php echo $this->url('en'); ?>" class="btn_snav">Home</a>
                        </li>
                        <li>
                            <a target="_blank" href="<?php echo $this->url('en-case'); ?>" class="btn_snav">Projects</a>
                        </li>
                        <li>
                            <a target="_blank" href="<?php echo $this->url('en-about'); ?>" class="btn_snav">About</a>
                        </li>
                        <li>
                            <a target="_blank" href="<?php echo $this->url('home'); ?>" class="btn_snav hide-english">中文</a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="En_btn"><span class="nav_line"></span> <a href="<?php echo $this->url('home'); ?>" class="btn_nav">中文</a></li>
        </ul>
    </div>
</div>
<div class="content">
    <?php echo $this->content; ?>
</div> <!-- /container -->
<footer>
    <div class="container foot">
        <div class="row">
            <div class="col-md-3 col-sm-3 col-xs-12"></div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="row font-talk" style="padding: 0 50px">
                    <div class="col-md-3 col-sm-3 col-xs-3">
                        <a href="" class="twitter"></a>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-3">
                        <a href="" class="youtube"></a>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-3">
                        <a href="" class="facebook"></a>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-3">
                        <a href="" class="linkedin"></a>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12"></div>
        </div>
        <div class="row bottom-link">
            <div class="col-md-3 col-sm-3 col-xs-12"></div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <ul>
                    <li><a href="<?php echo $this->url('en-about'); ?>">About</a> <span class="link-line"></span></li>
                    <li><a href="">News</a><span class="link-line"></span></li>
                    <li><a href="<?php echo $this->url('en-case'); ?>">Projects</a><span class="link-line"></span></li>
                    <li><a href="<?php echo $this->url('en-about'); ?>">Contact</a></li>
                </ul>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-12"></div>
        </div>
        <p class="recording">
            © 2017 Shenzhen Rayvision Technology Co., Ltd. Y ICP B No.12028569-3
        </p>
    </div>
</footer>
<?php
$this->inlineScript()->appendFile($this->basePath('js/pages/layout.js'));
?>
<?php echo $this->inlineScript() ?>
</body>
</html>
