<?php
$this->headTitle($this->headTitle);
$this->headMeta()
    ->appendName('description', $this->description)
    ->appendName('keywords', $this->keywords);
?>
<div class="main-container" id="about-page">
    <div class="ab-banner">
        <img src="<?php echo $this->basePath('img/about/about_first.jpg')?>" class="" alt="rayvision" />
        <div class="container ab-banner-info">
            <div class="row">
                <h3>THE MOST USER-FRIENDLY VISUALCLOUD COMPUTING PLATFORM</h3>
                <h2>最贴近用户的视觉云计算服务平台</h2>
            </div>
        </div>
    </div>
    <div class="about-intro" id="about-intro">

      <h3>PIONEERING SELF-SERVICE CLOUD RENDER FARM</h3>
<span>Shenzhen Rayvision Technology Co., Ltd. is the largest cloud render farm in Asia dedicated to researching cluster renderings and providing cloud rendering computing services for computer animation, film special effects, television animation, architectural design performance, urban planning, game title animation and commercial advertising industry around the world. Known as China’s "Self-Service Cloud Render Farm" pioneer and Asia's largest cloud render farm, a global strategic partner of Alibaba Cloud. It includes three major brands which are RenderBus & Fox Renderfarm—Asia's largest cloud render farm, VIVUE.io—Better efficient review platform for video content collaboration and RaySync—The leading data transmission core technology provider. Rayvision could help improve the work efficiency and inspire the unlimited imagination & creativity for production teams!</span>
 <span>Most of the Rayvision Technology technical team members come from the world's leading film and television production company. Since its launch, it has been well received by the industry with its patented cloud rendering system and professional TD service team. With more than 60,000 users worldwide, RenderBus & Fox Renderfarm serves customers in over 50 countries, including Oscar winners, world-class movie & animation studios, special effects studios worldwide and most of the mainstream domestic animation companies in China.</span>
  <span>With a team of more than 20 years of CG experience, Rayvision Technology brings together elites from the United States, Singapore, India, Taiwan and Hong Kong, and have experience in the world's leading film and animation production companies including Disney, Lucasfilm, DreamWorks Animation and Sony Pictures. In CG rendering optimization & high-performance computing, Rayvision Technology has invested a lot of research resources dedicated to providing CG studios around the world efficient and convenient cloud rendering services.</span>
  <span>In 2014, Rayvision Technology launched a new global unified brand "Rayvision" based on the domestic brand RenderBus and its overseas sister brand Fox Renderfarm in order to provide consistent service to domestic and overseas CG studios. In 2017, Rayvision Technology has added two major products VIVUE.io—Better efficient review platform for video content collaboration & RaySync—The leading data transmission core technology provider in order to provide the global visual cloud computing industry with more high-quality, comprehensive, stable, efficient and convenient integrated services.</span>
   </div>
    <div class="about-aptitude" id="about-aptitude">
        <div class="container">
            <h3>RAYVISION QUALIFICATIONS</h3>
            <div class="row" style="margin-top: 70px">
             <div class="col-lg-2 col-md-2 col-sm-4 col-xs-4" style="padding-left: 0px;padding-right: 0px">
                <img src="<?php echo $this->basePath('img/about/aptitude01.png')?>">
                 <div class="aptitude-font">
                     Intellectual Property Management System Certification
                 </div>
             </div>
                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-4" style="padding-left: 0px;padding-right: 0px">
                    <img src="<?php echo $this->basePath('img/about/aptitude02.png')?>">
                    <div class="aptitude-font">
                        National High-tech Enterprise Certification
                    </div>
                </div>
                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-4" style="padding-left: 0px;padding-right: 0px">
                    <img src="<?php echo $this->basePath('img/about/aptitude03.png')?>">
                    <div class="aptitude-font">
                        China Cloud Rendering Platform Leading Enterprise Award
                    </div>
                </div>
                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-4" style="padding-left: 0px;padding-right: 0px">
                    <img src="<?php echo $this->basePath('img/about/aptitude04.png')?>">
                    <div class="aptitude-font">
                        CSEEA Software Enterprise Certificate
                    </div>
                </div>
                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-4" style="padding-left: 0px;padding-right: 0px">
                    <img src="<?php echo $this->basePath('img/about/aptitude05.png')?>">
                    <div class="aptitude-font">
                        International Market Development Award
                    </div>
                </div>
                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-4" style="padding-left: 0px;padding-right: 0px">
                    <img src="<?php echo $this->basePath('img/about/aptitude06.png')?>">
                    <div class="aptitude-font">
                        Oscar Winning Entries
                        <br> Service Team
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="about-develop" id="about-develop">
        <div class="container">
            <h3>COMPANY MILESTONES</h3>
            <div class="develop-content">
                <div class="develop1">
                    <span class="develop-year">2010</span><br>
                    <span class="develop-event">Found Renderbus </span>
                </div>
                <div class="develop2">
                    <span class="develop-year">2012</span><br>
                    <span class="develop-event">Found Fox Renderfarm</span>
                </div>
                <div class="develop3">
                    <span class="develop-year">2013</span><br>
                    <span class="develop-event">Warszawa</span>
                    <span class="develop-event">Krrish 3</span>
                    <span class="develop-event">Tekken</span>
                </div>
                <div class="develop4">
                    <span class="develop-year">2014</span><br>
                    <span class="develop-event">Found RAYVISION</span>
                    <span class="develop-event">Mr Hublot</span>
                    <span class="develop-event">Dragon Nest</span>
                    <span class="develop-event">The Legend of Qin</span>
                    <span class="develop-event">10000 Years Later</span>
                    <span class="develop-event">……</span>
                </div>
                <div class="develop5">
                    <span class="develop-year">2015</span><br>
                    <span class="develop-event">Alibaba Cloud strategic</span>
                    <span class="develop-event">Baahubali: The Beginning</span>
                    <span class="develop-event">Blinky Bill</span>
                    <span class="develop-event">Bilal</span>
                    <span class="develop-event">……</span>
                </div>
                <div class="develop6">
                    <span class="develop-year">2016</span><br>
                    <span class="develop-event">China Cloud Rendering </span>
                    <span class="develop-event">Platform Leading Enterprise</span>
                    <span class="develop-event">Monkey King: King of Heroes </span>
                    <span class="develop-event">Throne of Elves</span>
                    <span class="develop-event">I AM NEZHA</span>
                    <span class="develop-event">L.O.R.D</span>
                    <span class="develop-event">Final Fantasy</span>
                    <span class="develop-event">……</span>
                </div>
                <div class="develop7">
                    <span class="develop-year">2017</span><br>
                    <span class="develop-event">Found Vivue.io</span>
                    <span class="develop-event">Found RaySync</span>
                    <span class="develop-event">International Market</span>
                    <span class="develop-event">Wolf Warriors Ⅱ</span>
                    <span class="develop-event">Baahubali 2: The Conclusion</span>
                    <span class="develop-event">Duckweed</span>
                    <span class="develop-event">ICE FANTASY</span>
                    <span class="develop-event">To the Sky Kingdom</span>
                    <span class="develop-event">……</span>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="develop-content2">
                <div class="develop1">
                    <span class="develop-year">2010</span><br>
                    <span class="develop-event">Found Renderbus </span>
                </div>
                <div class="develop2">
                    <span class="develop-year">2012</span><br>
                    <span class="develop-event">Found Fox Renderfarm</span>
                </div>
                <div class="develop3">
                    <span class="develop-year">2013</span><br>
                    <span class="develop-event">Warszawa</span>
                    <span class="develop-event">Krrish 3</span>
                    <span class="develop-event">Tekken</span>
                </div>
                <div class="develop4">
                    <span class="develop-year">2014</span><br>
                    <span class="develop-event">Found RAYVISION</span>
                    <span class="develop-event">Mr Hublot</span>
                    <span class="develop-event">Dragon Nest</span>
                    <span class="develop-event">The Legend of Qin</span>
                    <span class="develop-event">10000 Years Later</span>
                    <span class="develop-event">……</span>
                </div>
                <div class="develop5">
                    <span class="develop-year">2015</span><br>
                    <span class="develop-event">Alibaba Cloud strategic partner</span>
                    <span class="develop-event">Baahubali: The Beginning</span>
                    <span class="develop-event">Blinky Bill</span>
                    <span class="develop-event">Bilal</span>
                    <span class="develop-event">……</span>
                </div>
                <div class="develop6">
                    <span class="develop-year">2016</span><br>
                    <span class="develop-event">China Cloud Rendering </span>
                    <span class="develop-event">Platform Leading Enterprise Award</span>
                    <span class="develop-event">Monkey King: King of Heroes </span>
                    <span class="develop-event">Throne of Elves</span>
                    <span class="develop-event">I AM NEZHA</span>
                    <span class="develop-event">L.O.R.D</span>
                    <span class="develop-event">Final Fantasy</span>
                    <span class="develop-event">……</span>
                </div>
                <div class="develop7">
                    <span class="develop-year">2017</span><br>
                    <span class="develop-event">Found Vivue.io</span>
                    <span class="develop-event">Found RaySync</span>
                    <span class="develop-event">International Market</span>
                    <span class="develop-event">Wolf Warriors Ⅱ</span>
                    <span class="develop-event">Baahubali 2: The Conclusion</span>
                    <span class="develop-event">Duckweed</span>
                    <span class="develop-event">ICE FANTASY</span>
                    <span class="develop-event">Ten great III of peach blossom</span>
                    <span class="develop-event">……</span>
                </div>
            </div>
        </div>
    </div>
    <div class="about-join" id="about-join">
        <img src="<?php echo $this->basePath('img/about/aboutcollege.png')?>" class="" alt="rayvision" />
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-sm-4 col-xs-12 about-left"></div>
                <div class="col-md-8 col-sm-8 col-xs-12 about-middle">
                    <h3>JOIN US</h3>
                  <span>We build an open and unobstructed working environment for everyone. We focus on the quality of life and work-life balance. It is filled with challenge and passion. We endeavor to create a free working atmosphere, allowing everyone to give full rein to their advantages and abilities. We always do our best.</span>
                 <span>In Rayvision, we are not only colleagues but also family members. There are regular indoor and outdoor activities, such as tea party on Wednesdays, basketball game on Thursdays, swimming club, barbecue and occasional travel. Come and join us!</span>

                </div>
            </div>
        </div>
    </div>

    <div class="about-ability" id="about-ability">
            <h2>TECHNOLOGY CAPABILITIES</h2>
        <div class="row">
            <div class="col-md-4 col-sm-4 col-xs-12 abilitycontent">
                <img src="<?php echo $this->basePath('img/about/about_11.png')?>" class="" alt="rayvision" />
                <h3>Large-scale Cluster Scheduling</h3>
                <span>Our proprietary job distribution scheduling engine is able to easily manage millions of render jobs and tens of thousands of render nodes.</span>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12 abilitycontent">
                <img src="<?php echo $this->basePath('img/about/about_12.png')?>" class="" alt="rayvision" />
                <h3>High-performance Storage System</h3>
                <span>Possesses massive high-performance SSD storage system that stores customer source files to solve the I/O bottleneck.</span>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12 abilitycontent">
                <img src="<?php echo $this->basePath('img/about/about_13.png')?>" class="" alt="rayvision" />
                <h3>Data Synchronization Algorithm</h3>
                <span>In addition to high-speed transmission, our Aspera engine is also capable of encrypting data during the transmission process, ensuring data is secured.</span>
            </div>
        </div>
    </div>
    <div class="about-bottom" id="about-bottom">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-4 col-xs-12">
                    <h3>CONTACT US</h3>
                    <div class="bottom-line"></div>
                    <ul class="contact-info">
                        <li>Shenzhen-Global Headquarters</li>
                        <li><a href="tel:4000034560"><i class="fa fa-comments-o"></i>Tel: +86 755-82552100</a></li>
                        <li><a href="tel:+8675582552100"><i class="fa fa-phone"></i> Fax: +86 755-82557919</a></li>
                        <li><i class="fa fa-envelope"></i>  Mail:<a href="mailto:service@foxrenderfarm.com">service@foxrenderfarm.com</a></li>
                        <li><i class="fa fa-map-marker"></i>
                            Address: 17th Floor, Building B, Sunny Kechuang Center,
                            No.1024 Nanxin Road, Nanshan District, Shenzhen,
                            Guangdong, P.R. China 518000

                        </li>
                    </ul>
                </div>
                <div class="col-md-6 col-sm-8 col-xs-12">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3685.719606431827!2d113.91210931545552!3d22.51470098521257!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3403ee50f0307c9f%3A0xef502d1bada522fc!2sSunny+Kechuang+Center!5e0!3m2!1sen!2sus!4v1502864612844;

" width="568" height="328" frameborder="0" style="border:0" allowfullscreen></iframe>
                </div>
            </div>
             <div class="row about-connect" id="about-connect">
                 <div class="col-xs-12 col-sm-4 col-md-4">
                  <p>Fox Renderfarm</p>
                  <p>Tel：18612698101</p>
                  <p><a href="mailto:weller@rayvision.com">Mail:weller@rayvision.com</a></p>
                 </div>
                 <div class="col-xs-12 col-sm-4 col-md-4">
                     <p>VIVUE.io</p>
                     <p>Tel：13723402520/13510709299 (Mike)</p>
                     <p><a href="mailto:vivue@rayvision.com">Mail：vivue@rayvision.com</a></p>
                 </div>
                 <div class="col-xs-12 col-sm-4 col-md-4">
                     <p>Raysync</p>
                     <p>Tel：18948780646</p>
                     <p><a href="mailto:walken@rayvision.com">Mail：walken@rayvision.com</a></p>
                 </div>
             </div>
        </div>
    </div>
</div>
