<?php
$this->headTitle($this->headTitle);
$this->headMeta()
    ->appendName('description', $this->description)
    ->appendName('keywords', $this->keywords);
?>
<?php
$this->headScript()->prependFile($this->basePath('js/pages/scrolloverflow.min.js'));
$this->headScript()->prependFile($this->basePath('js/pages/jquery.fullPage.js'));
$this->headScript()->prependFile($this->basePath('js/pages/index/wow.min.js'));
?>

<style>

    /* Backgrounds will cover all the section
    * --------------------------------------- */
    #section0,
    #section1,
    #section2,
    #section3{
        background-size: cover;
        background-attachment: fixed;
    }

    /* Defining each sectino background and styles
    * --------------------------------------- */
    #section0{
        background-image: url("../img/case/case_bg.jpg");
        background-size: cover;
    }
    #section0 h1{
        top: 50%;
        transform: translateY(-50%);
        position: relative;
    }
     #section6{
             background-image: url("../img/case/bahubali.jpg");
             background-size: cover;
             background-position: center;
             /*padding: 6% 0 0 0;*/
    }
    #section1{
        background-image: url("../img/case/case_hublot.jpg");
        background-size: cover;
        background-position: center;
        /*padding: 6% 0 0 0;*/
    }
    #section2{
        background-image: url("../img/case/case_dsgl.jpg");
        /*padding: 6% 0 0 0;*/
    }
    #section3{
        background-image: url("../img/case/case_zl.jpg");
        /*padding: 6% 0 0 0;*/
    }
    #section4{
        background-image: url("../img/case/benner2en.jpg");
        background-size: cover;
        background-position: center;
        /*padding: 6% 0 0 0;*/
    }

    #section3 h1{
        color: #000;
    }




    /* Bottom menu
    * --------------------------------------- */
    #infoMenu li a {
        color: #fff;
    }
</style>
<script type="text/javascript">
    $(document).ready(function() {
        $('#fullpage').fullpage({
            verticalCentered: false,

            //to avoid problems with css3 transforms and fixed elements in Chrome, as detailed here: https://github.com/alvarotrigo/fullPage.js/issues/208
            css3:false
        });
    });
    new WOW().init();
</script>
<div class="main-container" id="case-page" >

    <div id="fullpage">
        <div class="section case-one" id="section0">
            <div class="container wow bounceInUp" data-wow-duration="1s" style=" position: relative; height: 100%">
                <div class="row case-first">
                    <div class="col-md-6 case-first-text" >
                        <img src="<?php echo $this->basePath('img/case/case_star.png')?>" class="star_img">
                        <div class="first-text">
                            <h3>RAYVISION CUSTOMERS AS
                                BRIGHT AS THE STARS</h3>
                            <span>
                                Rayvision customers are from the world's top animated film production studios, special effects studios and most of the mainstream animation companies from 50 countries and regions, including Oscar winners.
                          </span>
                        </div>

                    </div>
                    <div class="col-md-6">&nbsp;</div>
                </div>
                <div class="row case-first-logo">
                    <div class="col-md-6 col-sm-6 col-xs-12 logo-first">
                        <img src="<?php echo $this->basePath('img/case/case_logo1.png')?>">
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-12 logo-first" >
                        <img src="<?php echo $this->basePath('img/case/case_logo2.png')?>">
                    </div>
                </div>
                <div class="row case-second-logo">
                    <div class="col-md-6 col-sm-6 col-xs-12 logo-first">
                        <img src="<?php echo $this->basePath('img/case/case_logo3.png')?>">
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-12 logo-first">
                        <img src="<?php echo $this->basePath('img/case/case_logo4.png')?>">
                    </div>
                </div>
                <a href="javascript:;" class="ic_pagearr"></a>
            </div>
        </div>
        <div class="section case-six" id="section6">
            <div class="container" style="height: 100%">
                <div class="row" style="height: 100%">
                    <div class="col-md-7 col-sm-1 col-xs-12" style="display: none">&nbsp;</div>
                    <div class="col-md-5 col-sm-5 col-xs-12 case-common-text" >
                        <div class="second-top">
                            <!--                        <div class="img-content"> <img src="--><?php //echo $this->basePath('img/case/case_add.png')?><!--" class="img-add"></div>-->
                            <h5>Fox Renderfarm Cloud Rendering Works</h5>
                            <h3>Baahubali 2:<br>
                                The Conclusion</h3>
                            <span>Amazing Fantasy Epic Film<br>
                                  The Most Popular Indian Movie in History
                            </span>

                            <div class="second-bottom">
                                <div class="row case-info-img">
                                </div>
                                <p>“This is a fantasy fairy tale kind of movie where India introduces its culture to the world. Visual brilliance, perfect portray of emotions and showcasing of Indian culture makes it worth watching!” - Hollywood Critic Grace Randolph
                                </p>
                                <p style="margin-top: 30px">Bahubali: India's answer to Gerard Butler's “300” - The Times of India</p>
                                <img src="<?php echo $this->basePath('img/case/case_d.png')?>" class="img-down">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="section case-second" id="section1">
            <div class="container" style="height: 100%">
                <div class="row" style="height: 100%">
                    <div class="col-md-7 col-sm-1 col-xs-12" style="display: none">&nbsp;</div>
                    <div class="col-md-5 col-sm-5 col-xs-12 case-common-text" >
                        <div class="second-top">
<!--                        <div class="img-content"> <img src="--><?php //echo $this->basePath('img/case/case_add.png')?><!--" class="img-add"></div>-->
                        <h5>Fox Renderfarm Cloud Rendering Works</h5>
                            <h3>Mr. Hublot</h3>
                            <span>Luxembourg 3D Animated Short Film (11 minutes),
                                 86th Academy Awards (Oscars 2014) Best Animated
                               Short Films
                            </span>

                            <div class="second-bottom">
                                <div class="row case-info-img">
                                    <div class="col-md-3 col-sm-3 col-xs-4">
                                        <img src="<?php echo $this->basePath('img/case/case_01.png')?>">
                                        <span>3D Animated</span>
                                    </div>
                                    <div class="col-md-5 col-sm-5 col-xs-6">
                                        <img src="<?php echo $this->basePath('img/case/case_03.png')?>">
                                        <span> 86th Oscars Best<br>
                                     Animated Short Films</span>
                                    </div>
                                </div>
                                <p>
                                    “As a small studio of 3D animation film in France, we need a lot of computing power to show our originality. This requires a great number of computers than those used in the studio. Computer rendering cannot be finished without external support. Finally, we find RAYVISION.”
                                    Laurent Witz, filmmaker of short films
                               </p>
                                <img src="<?php echo $this->basePath('img/case/case_d.png')?>" class="img-down">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="section case-three" id="section2">
            <div class="container" style="height: 100%">
                <div class="row" style="height: 100%">
                    <div class="col-md-7 col-sm-1 col-xs-12" style="display: none">&nbsp;</div>
                    <div class="col-md-5 col-sm-5 col-xs-12 case-common-text" >
<!--                        <div class="img-content"> <img src="--><?php //echo $this->basePath('img/case/case_add.png')?><!--" class="img-add"></div>-->
                        <h5>Fox Renderfarm Cloud Rendering Works</h5>
                        <h3>Monkey King: <br>
                            Hero is Back</h3>
                        <span>Adhere to strict attitude and high-quality technical support, passing the $150 Million mark in box office for domestic animation film.</span>
                        <div class="row case-info-img">
                            <div class="col-md-5 col-sm-5 col-xs-6" style="padding-left: 0px;padding-right: 0px">
                                <img src="<?php echo $this->basePath('img/case/case_04.png')?>">
                                <span>The 30th Golden Rooster Awards Best Art Film Award</span>
                            </div>
                            <div class="col-md-7 col-sm-7 col-xs-6" style="padding-left: 0px;padding-right: 0px">
                                <img src="<?php echo $this->basePath('img/case/case_05.png')?>">
                                <span>The 16th China Huabiao Film Awards Outstanding Feature Film Award</span>
                            </div>
                        </div>
                        <p>
                            “Monkey King: Hero is Back” is a 3D animated film based on the Chinese traditional myth “Journey to the West” and won the 30th Golden Rooster Award for Best Art Film Award and the 16th China Huabiao Film Awards for Outstanding Feature Film Award.
                       </p>

                        <img src="<?php echo $this->basePath('img/case/case_d.png')?>" class="img-down">

                    </div>
                </div>
            </div>
        </div>
        <div class="section case-four" id="section3">
            <div class="container" style="height: 100%">
                <div class="row" style="height: 100%">
                    <div class="col-md-7 col-sm-1 col-xs-12" style="display: none">&nbsp;</div>
                    <div class="col-md-5 col-sm-5 col-xs-12 case-common-text" >
<!--                        <img src="--><?php //echo $this->basePath('img/case/case_add.png')?><!--" class="img-add">-->
                        <h5>Fox Renderfarm Cloud Rendering Works</h5>
                        <h3>Wolf Warrior 2</h3>
                        <span>Breaks the new record of Chinese box office</span>
                        <div class="row case-info-img">
                            <div class="col-md-4 col-sm-4 col-xs-4" style="padding-left: 0px;padding-right: 0px;">
                                <img src="<?php echo $this->basePath('img/case/case_06.png')?>">
                                <span>China Film Week CJIFF Best Movie Award </span>
                            </div>
                            <div class="col-md-4  col-sm-4 col-xs-4" style="padding-left: 0px;padding-right: 0px;">
                                <img src="<?php echo $this->basePath('img/case/case_07.png')?>">
                                <span>The Best Works Award for Excellent Work</span>
                            </div>
                            <div class="col-md-4  col-sm-4 col-xs-4" style="padding-left: 0px;padding-right: 0px;">
                                <img src="<?php echo $this->basePath('img/case/case_08.png')?>">
                                <span>Chinese American Film Festival Best Movie Award</span>
                            </div>
                        </div>
                        <p>
                            The first day of screening has broken the box office record of $182 million in 96 hours, refreshing the record of single-day box office titles in Chinese film history and setting a new box office record of "The Fastest $150 Million" of Chinese movie history. The number of viewers in the Chinese market reached 140 million, making it one of the top screening movie in the history of global film history.
                      </p>

                        <img src="<?php echo $this->basePath('img/case/case_d.png')?>" class="img-down">

                    </div>
                </div>
            </div></div>
        <div class="section case-five" id="section4">
            <div class="container" style="height: 100%">
                <div class="row" style="height: 100%">
                    <div class="col-md-7 col-sm-1 col-xs-12" style="display: none">&nbsp;</div>
                    <div class="col-md-5 col-sm-5 col-xs-12 case-common-text" >
<!--                        <div class="img-content"> <img src="--><?php //echo $this->basePath('img/case/case_add.png')?><!--" class="img-add"></div>-->
                        <h5>VIVUE.io Review & Collaboration Platform Works</h5>
                        <h4>The 8th China International New Media Short Film Festival</h4>
                        <h3>International Jury Panel Review Platform</h3>
                        <span>
                         CSFF is a national-level international short film festival founded in 2010. Feng Xiaogang, Lu Chuan, Chen Kexin and Jiang Wenli have all served as chairpersons for the jury panel.
                       </span>
                        <div class="row case-info-img">
                            <div class="col-md-4 col-sm-4 col-xs-4" style="padding-left: 0px;padding-right: 0px;">
                                <img src="<?php echo $this->basePath('img/case/case_09.png')?>">
                                <span>KingBonn Award<br>
                                        &nbsp;&nbsp;
                                    </span>
                            </div>
                            <div class="col-md-4  col-sm-5 col-xs-4" style="padding-left: 0px;padding-right: 0px;">
                                <img src="<?php echo $this->basePath('img/case/case_010.png')?>">
                                <span>
                                   Reviewing & Collaboration at anytime and anywhere
                                </span>
                            </div>
                            <div class="col-md-4  col-sm-4 col-xs-4" style="padding-left: 0px;padding-right: 0px;">
                                <img src="<?php echo $this->basePath('img/case/case_11.png')?>">
                                <span>Accurate comments with real-time sync for each frame</span>
                            </div>
                        </div>
                        <p>
                            VIVUE.io is the official Video Content Review Platform partner for The 8th China International New Media Short Film Festival. VIVUE.io provides a perfect link between the Organizing Committee and juries from all over the world for better summarizing film results.
                       </p>


                    </div>
                </div>
                <div class="page-footer" style="line-height: 0px">
                    <footer>
                        <div class="container foot">
                            <div class="row">
                                <div class="col-md-3 col-sm-3 col-xs-12"></div>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <div class="row font-talk" style="padding: 0 50px">
                                        <div class="col-md-3 col-sm-3 col-xs-3">
                                            <a href="https://twitter.com/foxrenderfarm" class="twitter" target="_blank"></a>
                                        </div>
                                        <div class="col-md-3 col-sm-3 col-xs-3">
                                            <a href="https://www.youtube.com/user/RayvisionInc" class="youtube" target="_blank"></a>
                                        </div>
                                        <div class="col-md-3 col-sm-3 col-xs-3">
                                            <a href="https://www.facebook.com/rayvision.inc" class="facebook" target="_blank"></a>
                                        </div>
                                        <div class="col-md-3 col-sm-3 col-xs-3">
                                            <a href="http://www.linkedin.com/company/rayvision" class="linkedin" target="_blank"></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3 col-sm-3 col-xs-12"></div>
                            </div>
                            <div class="row bottom-link">
                                <div class="col-md-3 col-sm-3 col-xs-12"></div>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <ul>
                                        <li><a href="<?php echo $this->url('en-about'); ?>">About</a> <span class="link-line"></span></li>
                                        <li><a href="http://www.foxrenderfarm.com/news/main" target="_blank">News</a><span class="link-line"></span></li>
                                        <li><a href="<?php echo $this->url('en-case'); ?>">Projects</a><span class="link-line"></span></li>
                                        <li><a href="http://www.rayvision.com/en/about.html#about-bottom"">Contact</a></li>
                                    </ul>
                                </div>
                                <div class="col-md-3 col-sm-3 col-xs-12"></div>
                            </div>
                            <p class="recording">
                                © 2017 Shenzhen Rayvision Technology Co., Ltd. Y ICP B No.12028569-3
                            </p>
                        </div>
                    </footer>

                </div>
            </div>
        </div>
    </div>

</div>

