<?php
$this->headTitle($this->headTitle);
$this->headMeta()
    ->appendName('description', $this->description)
    ->appendName('keywords', $this->keywords);
?>
<?php
$this->headScript()->prependFile($this->basePath('js/pages/index/scrollReveal.min.js'));
$this->headScript()->prependFile($this->basePath('js/pages/index/jquery.mousewheel.min.js'));
$this->headScript()->prependFile($this->basePath('js/pages/index/jquery.slimscroll.min.js'));
$this->headScript()->prependFile($this->basePath('js/pages/index/ddfullscreenslider.js'));
?>
<div class="main-container" id="index-page" >
    <section id="dowebok" class="dd_fullscreenslider">
        <div class="slidewrapper">
            <article class="slide" id="rayvision">
                <div class="container" style="width: 1200px;  height: 100%; margin: 0 auto;">
                <div class="first">
                        <div class="first_center" data-scroll-reveal> </div>
                    <div class="first_center_text" data-scroll-reveal>
                            <h3>RAYVISION</h3>
                            <h3>VISUAL CLOUD</h3>
                           <p>COMPUTING PLATFORM</p>
                            <span class="first_text">Options for more than 85% CG studios </span>
                        </div>
                </div>
                </div>
                    <div id="container">
                        <video id="background_video" loop muted></video>
                        <div id="video_cover"></div>
                        <div id="overlay"></div>
                        <div id="video_controls">
                                      <span id="play">
                <!--                        <img src="play.png">-->
                                      </span>
                            <span id="pause">
                <!--                        <img src="pause.png">-->
                                      </span>
                        </div>

                    </div>
                <a href="javascript:;" class="ic_pagearr"></a>
            </article>

            <article class="slide second" id="rayvision2">
          <div class="container" id="second">
                  <div class="second_text" >
                      <img src="<?php echo $this->basePath('img/index/Renderfarm.png')?>">
             <h3>YOUR POWERFUL RENDER FARM</h3>
              <p>24 Hours Support  |  OSCAR Service Team  |  Massive Render Nodes  |  Hollywood Security</p>
              <a href="http://www.foxrenderfarm.com/" target="_blank">More</a>
              </div>
            <div class="second_img">
                <ul>
                    <li class="second_one">
                        <a class="second_img1"></a>
                        <div class="second_img1_info">
                            <p>Passing the $150 Million <br>
                                mark in Chinese box office
                            </p>
                        </div>
                    </li>
                    <li class="second_two"><a class="second_img2"></a>
                        <div class="second_img2_info">
                            <p>Breaks the new record of <br>
                                Chinese box office
                            </p>
                        </div>
                    </li>
                    <li class="second_three"><a class="second_img3"></a>
                        <div class="second_img3_info">
                            <p>86th Oscars Best Animated <br>
                                Short Films
                            </p>
                        </div>
                    </li>
                </ul>
            </div>


          </div>
            </article>

            <article class="slide three"id="rayvision3">
                <div class="container" id="three">
                    <div class="three_text">
                        <img src="<?php echo $this->basePath('img/index/raysync-en.png')?>">
                            <h3> ENTERPRISE LARGE FILE TRANSFER</h3>
                        <p>Perfect solution for cross-border transmission, long-distance transmission,<br>
                            transmission of large files and more</p>
                        <a href="https://www.raysync.io/" target="_blank">More</a>
                    </div>
                </div>

            </article>

            <article class="slide four" id="rayvision4">
              <div class="container" >
                  <div class="row">
                      <div class="col-md-1 col-sm-12 col-xs-12">&nbsp;</div>
                      <div class="col-md-10 col-sm-12 col-xs-12" style="padding: 0px" id="four-text">
                          <div class="four_text">
                              <img src="<?php echo $this->basePath('img/index/vivue_logo_w.png')?>">
                              <h3>BETTER EFFICIENT REVIEW PLATFORM FOR VIDEO CONTENT COLLABORATION!</h3>
                              <p>Solve your video content uploading, reviewing and team<br>
                                  collaboration issues at anytime and anywhere!</p>
                              <a href="https://www.vivue.io/" target="_blank">More</a>
                          </div>
                      </div>
                      <div class="col-md-1 col-sm-12 col-xs-12">&nbsp;</div>
                  </div>

                  <div class="page-footer" style="line-height: 0px;margin: 0 auto">
                      <footer>
                          <div class="foot">
                              <div class="row">
                                  <div class="col-md-3 col-sm-3 col-xs-2"></div>
                                  <div class="col-md-6 col-sm-6 col-xs-8">
                                      <div class="row font-talk" style="padding: 0 50px">
                                          <div class="col-md-3 col-sm-3 col-xs-3">
                                              <a href="https://twitter.com/foxrenderfarm" class="twitter" target="_blank"></a>
                                          </div>
                                          <div class="col-md-3 col-sm-3 col-xs-3">
                                              <a href="https://www.youtube.com/user/RayvisionInc" class="youtube" target="_blank"></a>
                                          </div>
                                          <div class="col-md-3 col-sm-3 col-xs-3">
                                              <a href="https://www.facebook.com/rayvision.inc" class="facebook" target="_blank"></a>
                                          </div>
                                          <div class="col-md-3 col-sm-3 col-xs-3">
                                              <a href="http://www.linkedin.com/company/rayvision" class="linkedin" target="_blank"></a>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                              <div class="row bottom-link">
                                  <div class="col-md-3 col-sm-3 col-xs-12"></div>
                                  <div class="col-md-6 col-sm-6 col-xs-12">
                                      <ul>
                                          <li><a href="<?php echo $this->url('en-about'); ?>">About</a> <span class="link-line"></span></li>
                                          <li><a href="http://www.foxrenderfarm.com/news/main" target="_blank">News</a><span class="link-line"></span></li>
                                          <li><a href="<?php echo $this->url('en-case'); ?>" >Projects</a><span class="link-line"></span></li>
                                          <li><a href="http://www.rayvision.com/en/about.html#about-bottom" >Contact</a></li>
                                      </ul>
                                  </div>
                                  <div class="col-md-3 col-sm-3 col-xs-12"></div>
                              </div>
                              <p class="recording">
                                  © 2017 Shenzhen Rayvision Technology Co., Ltd. Y ICP B No.12028569-3
                              </p>
                          </div>
                      </footer>

                  </div>
              </div>
            </article>
        </div>
    </section>
</div>

<script>
    var fss;
    $(function() {
        fss = new ddfullscreenslider({
            sliderid: 'dowebok',
            addHash: false
        });
    });
    window.scrollReveal = new scrollReveal();


//    鼠标滚动动画出现事件
    $('#dowebok').mousewheel(function(event, delta) {
        var selectedParent1 = $("#selected1").parent();
        var selectedParent2 = $("#selected2").parent();
        var selectedParent3 = $("#selected3").parent();
        var selectedParent4 = $("#selected4").parent();
       if(delta === -1){
           if(selectedParent1.hasClass("selected")){
     $("#second").css({"margin-top":"0px","opacity":"1"})
    }
    if(selectedParent2.hasClass("selected")){
        $("#three").css({"margin-top":"0px","opacity":"1"})
    }
    if(selectedParent3.hasClass("selected")){
        $("#four-text").css({"margin-top":"0px","opacity":"1"})
        $(".page-footer").css({"bottom":"0px","opacity":"1","margin-top":"-30px"})
    }
       }
       if(delta === 1){
           if(selectedParent3.hasClass("selected")){
               $("#second").css({"margin-top":"0px","opacity":"1"})
           }
           if(selectedParent4.hasClass("selected")){
               $("#three").css({"margin-top":"0px","opacity":"1"})
           }
       }


    });
// 键盘上下事件
    $(document).on('keyup',function (e) {
      var keyCode = e.keyCode;
      console.log(keyCode);
        var selectedParent1 = $("#selected1").parent();
        var selectedParent2 = $("#selected2").parent();
        var selectedParent3 = $("#selected3").parent();
        var selectedParent4 = $("#selected4").parent();
      if(keyCode === 40) {
          if (selectedParent1.hasClass("selected")) {
              $("#second").css({"margin-top": "0px", "opacity": "1"})
          }
          if (selectedParent2.hasClass("selected")) {
              $("#three").css({"margin-top": "0px", "opacity": "1"})
          }
          if (selectedParent3.hasClass("selected")) {
              $("#four-text").css({"margin-top": "0px", "opacity": "1"})
              $(".page-footer").css({"margin-bottom": "0px", "opacity": "1","margin-top":"-30px"})
          }
      }
      if(keyCode === 38) {
          if (selectedParent3.hasClass("selected")) {
              $("#second").css({"margin-top": "0px", "opacity": "1"})
          }
          if (selectedParent4.hasClass("selected")) {
              $("#three").css({"margin-top": "0px", "opacity": "1"})
          }
      }


    });


</script>
<?php
$this->inlineScript()->appendFile($this->basePath('js/pages/index/bideo.js'));
$this->inlineScript()->appendFile($this->basePath('js/pages/index/main.js'));
?>


