<div class="main-container" id="about-page">
    <div class="ab-banner">
        <img src="<?php echo $this->basePath('img/about/aboutbanner.jpg')?>" class="" alt="rayvision" />
    </div>
    <div class="about-intro" id="about-intro">

      <h3>中国自助式云渲染开创者</h3>
          <span>深圳市瑞云科技有限公司是一家专注于研究集群渲染，为全球电脑动画、电影特效、电视动画片、建筑设计表现、城市规划、游戏片头动画和商业广告行业提供云端渲染计算服务的亚洲最大云渲染农场。被誉为中国“自助式云渲染”的开创者，同时也是阿里云视觉云计算全球战略合作伙伴。旗下包含RenderBus亚洲最大的云渲染农场、更高效的VIVUE.io审片协作平台、领先的数据传输核心技术RaySync镭速传输解决方案三大品牌。协同合作，极大提高制作团队的工作效率，充分释放无限想象力和创意！</span>
   <br>
          <span>
瑞云技术团队大多来自全球顶尖的影视制作公司。自推出运营以来，以基于专利技术的云渲染系统和专业的TD服务团队获得业界一致好评。瑞云渲染服务客户遍布世界50多个国家，用户数量超过60000，其中包括奥斯卡奖得主、世界顶级动画电影制作公司、特效工作室以及国内大部分主流动画制作公司。</span>
  <br>
          <span>瑞云拥有一支超过20年CG经验的团队，汇集了来自美国、新加坡、印度、台湾、香港等各地的精英，拥有迪士尼、卢卡斯、梦工厂、索尼等全球顶尖电影制作公司的从业经验。在CG渲染优化、高性能计算方面投入了大量的研究资源，致力于为全球的CG工作室提供高效便捷的云渲染服务。</span>
  <br>
          <span>
为了对国内外的CG工作室提供一致性的服务，2014年，瑞云科技在国内品牌RenderBus和其海外姐妹品牌Fox Renderfarm的基础上，推出全新的全球统一品牌“RAYVISION”，2017年又将更高效的VIVUE.io审片协作平台和领先的数据传输核心技术RaySync镭速传输解决方案两大产品加入其中，为全球视觉云计算行业提供更加优质、稳定、高效、便捷的一体化服务。</span>

    </div>
    <div class="about-aptitude" id="about-aptitude">
        <div class="container">
            <h3>瑞云资质</h3>
            <div class="row">
             <div class="col-lg-2 col-md-2 col-sm-4 col-xs-4">
                <img src="<?php echo $this->basePath('img/about/aptitude01.png')?>">
                 <div class="aptitude-font">
                     知识产权管理<br>体系认证
                 </div>
             </div>
                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-4">
                    <img src="<?php echo $this->basePath('img/about/aptitude02.png')?>">
                    <div class="aptitude-font">
                        国家高新<br>
                        企业认证
                    </div>
                </div>
                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-4">
                    <img src="<?php echo $this->basePath('img/about/aptitude03.png')?>">
                    <div class="aptitude-font">
                        中国云渲染平台<br>
                        领军企业奖
                    </div>
                </div>
                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-4">
                    <img src="<?php echo $this->basePath('img/about/aptitude04.png')?>">
                    <div class="aptitude-font">
                        cseea软件<br>
                        企业证书
                    </div>
                </div>
                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-4">
                    <img src="<?php echo $this->basePath('img/about/aptitude05.png')?>">
                    <div class="aptitude-font">
                        国际市场<br>
                        开拓奖
                    </div>
                </div>
                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-4">
                    <img src="<?php echo $this->basePath('img/about/aptitude06.png')?>">
                    <div class="aptitude-font">
                        奥斯卡获奖<br>
                        作品
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="about-develop" id="about-develop">
        <div class="container">
            <h3>发展历程</h3>
            <div class="develop-content">
                <div class="develop1">
                    <span class="develop-year">2010年</span><br>
                    <span class="develop-event">Renderbus成立</span>
                </div>
                <div class="develop2">
                    <span class="develop-year">2012年</span><br>
                    <span class="develop-event">Fox Renderfarm成立</span>
                </div>
                <div class="develop3">
                    <span class="develop-year">2013年</span><br>
                    <span class="develop-event">华沙</span>
                    <span class="develop-event">印度超人3</span>
                    <span class="develop-event">铁拳</span>
                </div>
                <div class="develop4">
                    <span class="develop-year">2014年</span><br>
                    <span class="develop-event">RAYVISION成立</span>
                    <span class="develop-event">哈布洛先生</span>
                    <span class="develop-event">龙之谷</span>
                    <span class="develop-event">秦时明月</span>
                    <span class="develop-event">一万年以后</span>
                    <span class="develop-event">……</span>
                </div>
                <div class="develop5">
                    <span class="develop-year">2015年</span><br>
                    <span class="develop-event">瑞云阿里云战略合作</span>
                    <span class="develop-event">巴霍巴利王1</span>
                    <span class="develop-event">Blinky Bill</span>
                    <span class="develop-event">Bilal</span>
                    <span class="develop-event">……</span>
                </div>
                <div class="develop6">
                    <span class="develop-year">2016年</span><br>
                    <span class="develop-event">中国云渲染平台</span>
                    <span class="develop-event">领军企业奖</span>
                    <span class="develop-event">大圣归来</span>
                    <span class="develop-event">精灵王座</span>
                    <span class="develop-event">我是哪吒</span>
                    <span class="develop-event">爵迹</span>
                    <span class="develop-event">最终幻想</span>
                    <span class="develop-event">……</span>
                </div>
                <div class="develop7">
                    <span class="develop-year">2017年</span><br>
                    <span class="develop-event">Vivue.io成立</span>
                    <span class="develop-event">RaySync成立</span>
                    <span class="develop-event">国际市场开拓奖</span>
                    <span class="develop-event">战狼2</span>
                    <span class="develop-event">巴霍巴利王2</span>
                    <span class="develop-event">乘风破浪</span>
                    <span class="develop-event">幻城</span>
                    <span class="develop-event">熊出没·奇幻世界</span>
                    <span class="develop-event">三生三世十里桃花</span>
                    <span class="develop-event">……</span>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="develop-content2">
            <div class="circle"></div>
                <div class="develop-text">
                    <span class="develop-year">2017年</span><br>
                    <span class="develop-event">Vivue.io成立</span>
                    <span class="develop-event">RaySync成立</span>
                    <span class="develop-event">国际市场开拓奖</span>
                    <span class="develop-event">战狼2</span>
                    <span class="develop-event">巴霍巴利王2</span>
                    <span class="develop-event">乘风破浪</span>
                    <span class="develop-event">幻城</span>
                    <span class="develop-event">熊出没·奇幻世界</span>
                    <span class="develop-event">三生三世十里桃花</span>
                    <span class="develop-event">……</span>
                </div>
                <div class="circle"></div>
                <div class="develop-text">
                    <span class="develop-year">2016年</span><br>
                    <span class="develop-event">中国云渲染平台</span>
                    <span class="develop-event">领军企业奖</span>
                    <span class="develop-event">大圣归来</span>
                    <span class="develop-event">精灵王座</span>
                    <span class="develop-event">我是哪吒</span>
                    <span class="develop-event">爵迹</span>
                    <span class="develop-event">最终幻想</span>
                    <span class="develop-event">……</span>
                </div>

                <div class="circle"></div>
                <div class="develop-text">
                    <span class="develop-year">2015年</span><br>
                    <span class="develop-event">瑞云阿里云战略合作</span>
                    <span class="develop-event">巴霍巴利王1</span>
                    <span class="develop-event">Blinky Bill</span>
                    <span class="develop-event">Bilal</span>
                    <span class="develop-event">……</span>
                </div>
                <div class="circle"></div>
                <div class="develop-text">
                    <span class="develop-year">2014年</span><br>
                    <span class="develop-event">RAYVISION成立</span>
                    <span class="develop-event">哈布洛先生</span>
                    <span class="develop-event">龙之谷</span>
                    <span class="develop-event">秦时明月</span>
                    <span class="develop-event">一万年以后</span>
                    <span class="develop-event">……</span>
                </div>
                <div class="circle"></div>
                <div class="develop-text">
                    <span class="develop-year">2013年</span><br>
                    <span class="develop-event">华沙</span>
                    <span class="develop-event">印度超人3</span>
                    <span class="develop-event">铁拳</span>
                </div>
                <div class="circle"></div>
                <div class="develop-text">
                    <span class="develop-year">2012年</span><br>
                    <span class="develop-event">Fox Renderfarm成立</span>
                </div>
                <div class="circle"></div>
                <div class="develop-text">
                    <span class="develop-year">2010年</span><br>
                    <span class="develop-event">Renderbus成立</span>
                </div>
            </div>
        </div>
    </div>
    <div class="about-join" id="about-join">
        <img src="<?php echo $this->basePath('img/about/aboutcollege.png')?>" class="" alt="rayvision" />
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-sm-4 col-xs-12 about-left"></div>
                <div class="col-md-8 col-sm-8 col-xs-12 about-middle">
                    <h3>加入瑞云伐木累</h3>
                    <span>这里有自由的发挥空间，舒适的工作环境，有爱的团队氛围，超越同行的福利......这里充满了挑战和激情，业内精英与牛人大咖汇聚，头脑风暴与思维火花碰撞，每个人的优势和能力都得以充分发挥。我们全力以赴，我们力臻完美！</span>
                    <span>在这里，我们不仅是工作伙伴，更是家人。我们会定期举办各种户内外活动。每周三下午的茶话会，周四的篮球比赛，游泳俱乐部，户外烧烤，还有各种旅游，等你来加入！</span>
                       <a href="<?php echo $this->url('join-us'); ?>" class="more-btn">查看更多</a>

                </div>
            </div>
        </div>
    </div>

    <div class="about-ability" id="about-ability">
            <h2>技术能力</h2>
        <div class="row">
            <div class="col-md-4 col-sm-4 col-xs-12 abilitycontent">
                <img src="<?php echo $this->basePath('img/about/about_11.png')?>" class="" alt="rayvision" />
                <h3>大规模集群调度</h3>
                <span>瑞云的任务调度引擎能轻松管理上百万的渲染帧队列，并且能管理成百上千台渲染节点机。</span>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12 abilitycontent">
                <img src="<?php echo $this->basePath('img/about/about_12.png')?>" class="" alt="rayvision" />
                <h3>高性能存储</h3>
                <span>内部纯SSD阵列存放用户的源文件，千台服务器同时加载文件，像加载本地磁盘上的文件一样迅速。</span>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12 abilitycontent">
                <img src="<?php echo $this->basePath('img/about/about_13.png')?>" class="" alt="rayvision" />
                <h3>数据同步算法</h3>
                <span>内置的Aspera引擎除了能提供高速传输性能之外，还能对传输过程中的数据进行加密，保证数据安全。</span>
            </div>
        </div>
    </div>
    <div class="about-bottom" id="about-bottom">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-4 col-xs-12">
                    <h3>联系我们</h3>
                    <div class="bottom-line"></div>
                    <ul class="contact-info">
                        <li>深圳-全球总部</li>
                        <li><a href="tel:4000034560"><i class="fa fa-comments-o"></i> 24小时热线:400-0034560</a></li>
                        <li><a href="tel:+8675582552100"><i class="fa fa-phone"></i> 电话:0755-82552100</a></li>
                        <li><i class="fa fa-fax"></i> 传真:0755-82557919</li>
                        <li><i class="fa fa-envelope"></i> 电邮:<a href="mailto:service@rayvision.com">service@rayvision.com</a></li>
                        <li><i class="fa fa-map-marker"></i> 地址:深圳市南山区商华路2号阳光科创中心B座17层

                        </li>
                    </ul>
                </div>
                <div class="col-md-6 col-sm-8 col-xs-12">
                    <div style="width:570px;height:330px;border:#ccc solid 1px;" id="dituContent"></div>
                </div>
            </div>
             <div class="row about-connect">
                 <div class="col-xs-12 col-sm-4 col-md-4">
                  <p>渲染大客户合作</p>
                  <p>项目经理电话：18612698101</p>
                  <p><a href="mailto:weller@rayvision.com">邮 箱：weller@rayvision.com</a></p>
                 </div>
                 <div class="col-xs-12 col-sm-4 col-md-4">
                     <p>审片协助</p>
                     <p>电话：13723402520/13510709299(郑先生)</p>
                     <p><a href="mailto:vivue@rayvision.com">邮 箱：vivue@rayvision.com</a></p>
                 </div>
                 <div class="col-xs-12 col-sm-4 col-md-4">
                     <p>传输联系方式</p>
                     <p>咨询请拨：18948780646</p>
                     <p><a href="mailto:walken@rayvision.com">邮 箱：walken@rayvision.com</a></p>
                 </div>
             </div>
            <!--公司办事处-->
                <div class="row company-position">
                    <div class="col-xs-12 col-sm-4 col-md-4 company-office">
                        <p class="office-city">北京办事处</p>
                        <p class="office-tel"><a href="tel:+8601057136241"><i class="fa fa-phone"></i> 电话:010-57136241</a></p>
                        <p class="office-fax"><i class="fa fa-fax"></i> 传真:010-63922824</p>
                        <p class="office-address"><i class="fa fa-map-marker"></i> 地址:北京市朝阳区大成国际中心3号楼A座609室</p>
                    </div>

                    <div class="col-xs-12 col-sm-4 col-md-4 company-office">
                        <p class="office-city">上海办事处</p>
                        <p class="office-tel"><a href="tel:+8602164686019"><i class="fa fa-phone"></i> 电话:021-64686019</a></p>
                        <p class="office-fax"><i class="fa fa-fax"></i> 传真:021-64686018</p>
                        <p class="office-address"><i class="fa fa-map-marker"></i> 地址:上海市徐汇区裕德路168号徐汇商务大厦2020室</p>
                    </div>

                    <div class="col-xs-12 col-sm-4 col-md-4 company-office">
                        <p class="office-city">成都办事处</p>
                        <p class="office-tel"><a href="tel:+8602885875257"><i class="fa fa-phone"></i> 电话:028-85875257</a></p>
                        <p class="office-fax"><i class="fa fa-fax"></i> 传真:028-62821428</p>
                        <p class="office-address"><i class="fa fa-map-marker"></i> 地址:四川省成都市武侯区新光路1号观南上域5-2-602</p>
                    </div>
                </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="http://api.map.baidu.com/api?key=&v=1.1&services=true"></script>
<script type="text/javascript">
    //创建和初始化地图函数：
    function initMap(){
        createMap();//创建地图
        setMapEvent();//设置地图事件
        addMapControl();//向地图添加控件
        addMarker();//向地图中添加marker



    }

    //创建地图函数：
    function createMap(){
        var map = new BMap.Map("dituContent");//在百度地图容器中创建一个地图
        var point = new BMap.Point(113.920892,22.519803);//定义一个中心点坐标
        map.centerAndZoom(point,17);//设定地图的中心点和坐标并将地图显示在地图容器中
        window.map = map;//将map变量存储在全局
        var marker = new BMap.Marker(point);  // 创建标注
        map.addOverlay(marker);               // 将标注添加到地图中
//        marker.setAnimation(BMAP_ANIMATION_BOUNCE);

    }

    //地图事件设置函数：
    function setMapEvent(){
        map.enableDragging();//启用地图拖拽事件，默认启用(可不写)
        map.enableScrollWheelZoom();//启用地图滚轮放大缩小
        map.enableDoubleClickZoom();//启用鼠标双击放大，默认启用(可不写)
        map.enableKeyboard();//启用键盘上下左右键移动地图
    }

    //地图控件添加函数：
    function addMapControl(){
        //向地图中添加缩放控件
        var ctrl_nav = new BMap.NavigationControl({anchor:BMAP_ANCHOR_TOP_LEFT,type:BMAP_NAVIGATION_CONTROL_ZOOM});
        map.addControl(ctrl_nav);
        //向地图中添加缩略图控件
        var ctrl_ove = new BMap.OverviewMapControl({anchor:BMAP_ANCHOR_BOTTOM_RIGHT,isOpen:0});
        map.addControl(ctrl_ove);
        //向地图中添加比例尺控件
        var ctrl_sca = new BMap.ScaleControl({anchor:BMAP_ANCHOR_BOTTOM_LEFT});
        map.addControl(ctrl_sca);
    }

    //标注点数组
    var markerArr = [{title:"深圳市瑞云科技有限公司",content:"我的备注",point:"113.920892|22.519903",isOpen:0,icon:{w:23,h:25,l:46,t:21,x:9,lb:12}}
    ];
    //创建marker
    function addMarker(){
        for(var i=0;i<markerArr.length;i++){
            var json = markerArr[i];
            var p0 = json.point.split("|")[0];
            var p1 = json.point.split("|")[1];
            var point = new BMap.Point(p0,p1);
            var iconImg = createIcon(json.icon);
            var marker = new BMap.Marker(point,{icon:iconImg});
            var iw = createInfoWindow(i);
            var label = new BMap.Label(json.title,{"offset":new BMap.Size(json.icon.lb-json.icon.x+10,-20)});
            marker.setLabel(label);
            map.addOverlay(marker);
            label.setStyle({
                borderColor:"#808080",
                color:"#333",
                cursor:"pointer"
            });

            (function(){
                var index = i;
                var _iw = createInfoWindow(i);
                var _marker = marker;
                _marker.addEventListener("click",function(){
                    this.openInfoWindow(_iw);
                });
                _iw.addEventListener("open",function(){
                    _marker.getLabel().hide();
                })
                _iw.addEventListener("close",function(){
                    _marker.getLabel().show();
                })
                label.addEventListener("click",function(){
                    _marker.openInfoWindow(_iw);
                })
                if(!!json.isOpen){
                    label.hide();
                    _marker.openInfoWindow(_iw);
                }
            })()
        }
    }
    //创建InfoWindow
    function createInfoWindow(i){
        var json = markerArr[i];
        var iw = new BMap.InfoWindow("<b class='iw_poi_title' title='" + json.title + "'>" + json.title + "</b><div class='iw_poi_content'>"+json.content+"</div>");
        return iw;
    }
    //创建一个Icon
    //    function createIcon(json){
    //        var icon = new BMap.Icon("http://app.baidu.com/map/images/us_mk_icon.png", new BMap.Size(json.w,json.h),{imageOffset: new BMap.Size(-json.l,-json.t),infoWindowOffset:new BMap.Size(json.lb+5,1),offset:new BMap.Size(json.x,json.h)})
    ////        return icon;
    //    }

    initMap();//创建和初始化地图
</script>