<?php
$this->headTitle($this->headTitle);
$this->headMeta()
    ->appendName('description', $this->description)
    ->appendName('keywords', $this->keywords);
?>
<div class="main-container" id="about-page">
    <div class="ab-banner">
        <img src="<?php echo $this->basePath('img/about/about_first.jpg')?>" class="" alt="rayvision" />
        <div class="ab-banner-info">
            <div class="row">
<!--                <h3>THE MOST USER-FRIENDLY VISUALCLOUD COMPUTING PLATFORM</h3>-->
                <h2>RAYVISION视觉云计算服务平台</h2>
            </div>
        </div>
    </div>
    <div class="about-intro" id="about-intro">

      <h3>中国自助式云渲染开创者</h3>
        <span>瑞云科技是一家专注于为视觉行业提供垂直云计算SaaS服务的公司。用户包括全球领先的电脑动画工作室、影视特效工作室、建筑设计可视化工作室、游戏以及商业广告公司等。瑞云旗下的Renderbus云渲染平台是亚洲最大的云渲染农场，被誉为中国“自助式云渲染”的开创者。</span>
        <br>
        <span>除了渲染计算，瑞云还将陆续为视觉行业推出一系列满足行业用户需求的专业的云服务。目前瑞云对外已经开放的服务包括： Renderbus云渲染、VIVUE.io审片协作平台、RaySync镭速传输解决方案。三大服务，协同工作，使视觉行业的用户摆脱沉重的IT和计算设施投入，将更多的精力和资源放在艺术创作上，极大提高影视业生产与协作效率，从而推动整个行业快速发展。</span>
        <br>
        <span>瑞云自2010年推出第一个产品Renderbus以来，以基于专利技术的云渲染平台以及专业的TD服务团队，迅速获得业界一致好评，并在短短3年内取得了行业第一的市场地位。截止到2017年底，瑞云的客户遍布世界50多个国家，注册使用瑞云的工作室已经超过8万家，其中包括奥斯卡奖得主、世界顶级动画电影制作公司、特效工作室以及国内超过85%的主流动画制作公司。</span>
        <br>
        <span>瑞云的核心技术团队大多在影视行业从事技术研发工作超过10年，技术骨干来自美国、印度、澳洲、台湾等多个国家地区，他们在迪士尼、工业光魔、梦工场等工作室拥有多年的一线从业经验。同时，瑞云还拥有一支在并行计算、大规模集群管理与调度、高性能 I/O系统等专业方向经验丰富的系统开发团队。瑞云拥有的单集群5000节点集群系统，在国内外渲染领域遥遥领先，可以为不同规格的用户提供可灵活扩展、高弹性的渲染计算资源。
        </span>
        <br>
          <span>瑞云的投资方包括丝路视觉和阿里巴巴。丝路视觉是中国最领先的数字视觉方案综合提供商，而阿里巴巴除了电商以外，还拥有中国最大的公有云计算平台阿里云。
        </span>
    </div>
    <div class="about-aptitude" id="about-aptitude">
        <div class="container">
            <h3>瑞云资质</h3>
            <div class="row">
                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-4">
                    <img src="<?php echo $this->basePath('img/about/aptitude01.png')?>">
                    <div class="aptitude-font">
                        知识产权管理体系认证
                    </div>
                </div>
                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-4">
                    <img src="<?php echo $this->basePath('img/about/aptitude02.png')?>">
                    <div class="aptitude-font">
                        国家高新企业认证
                    </div>
                </div>
                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-4">
                    <img src="<?php echo $this->basePath('img/about/aptitude04.png')?>">
                    <div class="aptitude-font">
                        软件企业证书
                    </div>
                </div>
                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-4">
                    <img src="<?php echo $this->basePath('img/about/aptitude03.png')?>">
                    <div class="aptitude-font">
                        中国云渲染平台领军企业奖
                    </div>
                </div>
                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-4">
                    <img src="<?php echo $this->basePath('img/about/aptitude05.png')?>">
                    <div class="aptitude-font">
                        ISO27001安全认证
                    </div>
                </div>
                <div class="col-lg-2 col-md-2 col-sm-4 col-xs-4">
                    <img src="<?php echo $this->basePath('img/about/aptitude06.png')?>">
                    <div class="aptitude-font">
                        奥斯卡获奖作品
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="about-develop" id="about-develop">
        <div class="container">
            <h3>瑞云数据</h3>
            <div class="develop-content">
                <div class="develop-data">
                    <div class="container">
                        <div class="row data-row">
                            <div class="col-md-6 col-sm-6 col-xs-6">
                                <div class="col-md-4">
                                    <h4>8万+</h4>
                                    <p>注册用户&工作室</p>
                                </div>
                                <div class="col-md-4">
                                    <h4>500万</h4>
                                    <p>帧月输出</p>
                                </div>
                                <div class="col-md-4">
                                    <h4>200TB</h4>
                                    <p>图像月输出</p>
                                </div>
                            </div>
                            <div class="col-md-6">&nbsp;</div>
                        </div>
                        <div class="row data-row">
                            <div class="col-md-6 col-sm-6 col-xs-6">
                                <div class="col-md-4">
                                    <h4>10部<span style="font-size: 16px">/18部</span></h4>
                                    <p>2017国产3D动画渲染</p>
                                </div>
                                <div class="col-md-4">
                                    <h4>150+</h4>
                                    <p>员工（80%技术人员）</p>
                                </div>
                            </div>
                            <div class="col-md-6">&nbsp;</div>
                        </div>
                    </div>
                </div>

                <div class="develop1">
                    <span class="develop-year">2010年</span><br>
                    <span class="develop-event">Renderbus试运营</span>
                </div>
                <div class="develop2">
                    <span class="develop-year">2011年</span><br>
                    <span class="develop-event">Fox Renderfarm</span>
                    <span class="develop-event">海外平台试运营</span>
                    <span class="develop-event">铁拳</span>
                    <span class="develop-event">......</span>
                </div>
                <div class="develop3">
                    <span class="develop-year">2012年</span><br>
                    <span class="develop-event">丝路视觉战略投资</span>
                </div>
                <div class="develop4">
                    <span class="develop-year">2013年</span><br>
                    <span class="develop-event">华沙</span>
                    <span class="develop-event">印度超人3</span>
                    <span class="develop-event">......</span>
                </div>
                <div class="develop5">
                    <span class="develop-year">2014年</span><br>
                    <span class="develop-event">哈布洛先生</span>
                    <span class="develop-event">龙之谷</span>
                    <span class="develop-event">秦时明月</span>
                    <span class="develop-event">一万年以后</span>
                    <span class="develop-event">……</span>
                </div>
                <div class="develop6">
                    <span class="develop-year">2015年</span><br>
                    <span class="develop-event">瑞云阿里云战略合作</span>
                    <span class="develop-event">大圣归来</span>
                    <span class="develop-event">巴霍巴利王1</span>
                    <span class="develop-event">Blinky Bill</span>
                    <span class="develop-event">Bilal</span>
                    <span class="develop-event">……</span>
                </div>
                <div class="develop7">
                    <span class="develop-year">2016年</span><br>
                    <span class="develop-event">云渲染领军企业奖</span>
                    <span class="develop-event">最终幻想</span>
                    <span class="develop-event">乘风破浪</span>
                    <span class="develop-event">爵迹</span>
                    <span class="develop-event">精灵王座</span>
                    <span class="develop-event">……</span>
                </div>
                <div class="develop8">
                    <span class="develop-year">2017年</span><br>
                    <span class="develop-event">云渲染实现单集群5000节点</span>
                    <span class="develop-event">新服务VIVUE.io推出</span>
                    <span class="develop-event">新服务RaySync推出</span>
                    <span class="develop-event">高交会优秀产品奖</span>
                    <span class="develop-event">战狼2</span>
                    <span class="develop-event">巴霍巴利王2</span>
                    <span class="develop-event">幻城</span>
                    <span class="develop-event">熊出没·奇幻世界</span>
                    <span class="develop-event">三生三世十里桃花</span>
                    <span class="develop-event">……</span>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="develop-content2">
                <div class="circle"></div>
                <div class="develop-text">
                    <span class="develop-year">2017年</span><br>
                    <span class="develop-event">云渲染实现单集群5000节点</span>
                    <span class="develop-event">新服务VIVUE.io 推出</span>
                    <span class="develop-event">新服务Raysync推出</span>
                    <span class="develop-event">高交会优秀产品奖</span>
                    <span class="develop-event">战狼2</span>
                    <span class="develop-event">巴霍巴利王2</span>
                    <span class="develop-event">幻城</span>
                    <span class="develop-event">熊出没·奇幻世界</span>
                    <span class="develop-event">三生三世十里桃花</span>
                    <span class="develop-event">……</span>
                </div>
            <div class="circle"></div>
                <div class="develop-text">
                    <span class="develop-year">2016年</span><br>
                    <span class="develop-event">云渲染领军企业奖</span>
                    <span class="develop-event">最终幻想</span>
                    <span class="develop-event">乘风破浪</span>
                    <span class="develop-event">爵迹</span>
                    <span class="develop-event">精灵王座</span>
                    <span class="develop-event">……</span>
                </div>
                <div class="circle"></div>
                <div class="develop-text">
                    <span class="develop-year">2015年</span><br>
                    <span class="develop-event">瑞云阿里云战略合作</span>
                    <span class="develop-event">大圣归来</span>
                    <span class="develop-event">巴霍巴利王1</span>
                    <span class="develop-event">Blinky Bill</span>
                    <span class="develop-event">Bilal</span>
                    <span class="develop-event">……</span>
                </div>

                <div class="circle"></div>
                <div class="develop-text">
                    <span class="develop-year">2014年</span><br>
                    <span class="develop-event">哈布洛先生</span>
                    <span class="develop-event">龙之谷</span>
                    <span class="develop-event">秦时明月</span>
                    <span class="develop-event">一万年以后</span>
                    <span class="develop-event">……</span>
                </div>
                <div class="circle"></div>
                <div class="develop-text">
                    <span class="develop-year">2013年</span><br>
                    <span class="develop-event">华沙</span>
                    <span class="develop-event">印度超人3</span>
                    <span class="develop-event">......</span>
                </div>
                <div class="circle"></div>
                <div class="develop-text">
                    <span class="develop-year">2012年</span><br>
                    <span class="develop-event">丝路视觉战略投资</span>
                </div>
                <div class="circle"></div>
                <div class="develop-text">
                    <span class="develop-year">2011年</span><br>
                    <span class="develop-event">Fox Renderfarm海外平台试运营</span>
                    <span class="develop-event">铁拳</span>
                    <span class="develop-event">......</span>
                </div>
                <div class="circle"></div>
                <div class="develop-text">
                    <span class="develop-year">2010年</span><br>
                    <span class="develop-event">Renderbus试运营</span>
                </div>
            </div>
        </div>
    </div>
    <div class="about-ability" id="about-ability">
        <h2>技术能力</h2>
        <div class="row">
            <div class="col-md-4 col-sm-4 col-xs-12 abilitycontent">
                <img src="<?php echo $this->basePath('img/about/about_11.png')?>" class="" alt="rayvision" />
                <h3>大规模集群调度</h3>
                <span style="color: #666666;display: block; padding-left: 8%;padding-right: 8%;">瑞云的任务调度引擎能轻松管理上百万的渲染帧队列，毫秒级调度，单集群能管理5000节点，远超业界平均水平。</span>
                <p style="visibility: hidden">瑞云的任务调度</p>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12 abilitycontent">
                <img src="<?php echo $this->basePath('img/about/about_12.png')?>" class="" alt="rayvision" />
                <h3>高性能存储</h3>
                <span  style="color: #666666;display: block; padding-left: 8%;padding-right: 8%;">分布式高性能内部存储系统，综合使用SSD、内存等多级缓存加速，彻底解决渲染过程中资源访问卡顿问题，数千台服务器同时渲染时，像加载本地磁盘文件一样毫无延迟。</span>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12 abilitycontent">
                <img src="<?php echo $this->basePath('img/about/about_13.png')?>" class="" alt="rayvision" />
                <h3>数据同步算法</h3>
                <span  style="color: #666666;display: block; padding-left:8%;padding-right: 8%;">内置瑞云自研的镭速传输引擎，除了能提供高速数据传输之外，还能对传输过程中的数据进行加密，保证数据安全，比Aspera更稳定，更高效。
                <p style="visibility: hidden">瑞云的任务调度</p></span>
            </div>
        </div>
    </div>
    <div class="about-join" id="about-join">
        <img src="<?php echo $this->basePath('img/about/aboutcollege.png')?>" class="" alt="rayvision" />
        <div class="container">
            <div class="row" style="margin-left: 0px;margin-right: 0px">
                <div class="col-md-4 col-sm-4 col-xs-12 about-left"></div>
                <div class="col-md-8 col-sm-8 col-xs-12 about-middle">
                    <h3>加入瑞云伐木累</h3>
                    <span>这里有自由的发挥空间，舒适的工作环境，有爱的团队氛围，超越同行的福利......这里充满了挑战和激情，业内精英与牛人大咖汇聚，头脑风暴与思维火花碰撞，每个人的优势和能力都得以充分发挥。我们全力以赴，我们力臻完美！</span>
                    <span>在这里，我们不仅是工作伙伴，更是家人。我们会定期举办各种户内外活动。每周三下午的茶话会，周四的篮球比赛，游泳俱乐部，户外烧烤，还有各种旅游，等你来加入！</span>
                       <a href="<?php echo $this->url('join-us'); ?>" class="more-btn">查看更多</a>

                </div>
            </div>

        </div>
    </div>

    <div class="about-bottom" id="about-bottom">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-4 col-xs-12">
                    <h3>联系我们</h3>
                    <div class="bottom-line"></div>
                    <ul class="contact-info">
                        <li>深圳总部</li>
                        <li><a href="tel:4000034560"><i class="fa fa-comments-o"></i> 24小时热线：400-0034560</a></li>
                        <li><a href="tel:+8675582552100"><i class="fa fa-phone"></i> 电话：0755-82552100</a></li>
                        <li><i class="fa fa-fax"></i> 传真：0755-82557919</li>
                        <li><i class="fa fa-envelope"></i> 电邮：<a href="mailto:service@rayvision.com">service@rayvision.com</a></li>
                        <li><i class="fa fa-map-marker"></i> 地址：深圳市南山区商华路2号阳光科创中心B座17层

                        </li>
                    </ul>
                </div>
                <div class="col-md-6 col-sm-8 col-xs-12">
                    <div style="width:570px;height:330px;border:#ccc solid 1px;" id="dituContent"></div>
                </div>
            </div>
             <div class="row about-connect">
                 <div class="col-xs-12 col-sm-4 col-md-4">
                  <p>渲染大客户合作</p>
                  <p>18612698101（冯先生）</p>
                  <p><a href="mailto:weller@rayvision.com">weller@rayvision.com</a></p>
                 </div>
                 <div class="col-xs-12 col-sm-4 col-md-4">
                     <p>VIVUE审片协作产品</p>
                     <p>13510709299 ( Mike )</p>
                     <p><a href="mailto:vivue@rayvision.com">vivue@rayvision.com</a></p>
                 </div>
                 <div class="col-xs-12 col-sm-4 col-md-4">
                     <p>RaySync镭速传输产品</p>
                     <p>18948780646（黄先生）</p>
                     <p><a href="mailto:walken@rayvision.com">walken@rayvision.com</a></p>
                 </div>
             </div>
            <!--公司办事处-->
                <div class="row company-position">
                    <div class="col-xs-12 col-sm-4 col-md-4 company-office">
                        <p class="office-city">北京办事处</p>
                        <p class="office-tel"><a><i class="fa fa-phone"></i> 18948780640（谢先生）</a></p>
                        <p class="office-fax"><a href="mailto:mark@rayvision.com">mark@rayvision.com</a></p>
                        <p class="office-address"><i class="fa fa-map-marker"></i> 北京市朝阳区大成国际中心3号楼A座609室</p>
                    </div>

                    <div class="col-xs-12 col-sm-4 col-md-4 company-office">
                        <p class="office-city">上海办事处</p>
                        <p class="office-tel"><a><i class="fa fa-phone"></i>13402051543（周先生）</a></p>
                        <p class="office-fax"><a href="mailto:tomzhou@rayvision.com">tomzhou@rayvision.com</a> </p>
                        <p class="office-address"><i class="fa fa-map-marker"></i> 上海市静安区灵石路891号A座203室</p>
                    </div>

                    <div class="col-xs-12 col-sm-4 col-md-4 company-office">
                        <p class="office-city">成都办事处</p>
                        <p class="office-tel"><a><i class="fa fa-phone"></i> 18180777293（陈先生）</a></p>
                        <p class="office-fax"><a href="mailto:chenfh@rayvision.com">chenfh@rayvision.com</a> </p>
                        <p class="office-address"><i class="fa fa-map-marker"></i> 成都市双流区航都大街燕楠国际503</p>
                    </div>
                </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="http://api.map.baidu.com/api?key=&v=1.1&services=true"></script>
<script type="text/javascript">
    //创建和初始化地图函数：
    function initMap(){
        createMap();//创建地图
        setMapEvent();//设置地图事件
        addMapControl();//向地图添加控件
        addMarker();//向地图中添加marker



    }

    //创建地图函数：
    function createMap(){
        var map = new BMap.Map("dituContent");//在百度地图容器中创建一个地图
        var point = new BMap.Point(113.920892,22.519803);//定义一个中心点坐标
        map.centerAndZoom(point,17);//设定地图的中心点和坐标并将地图显示在地图容器中
        window.map = map;//将map变量存储在全局
        var marker = new BMap.Marker(point);  // 创建标注
        map.addOverlay(marker);               // 将标注添加到地图中
//        marker.setAnimation(BMAP_ANIMATION_BOUNCE);

    }

    //地图事件设置函数：
    function setMapEvent(){
        map.enableDragging();//启用地图拖拽事件，默认启用(可不写)
        map.enableScrollWheelZoom();//启用地图滚轮放大缩小
        map.enableDoubleClickZoom();//启用鼠标双击放大，默认启用(可不写)
        map.enableKeyboard();//启用键盘上下左右键移动地图
    }

    //地图控件添加函数：
    function addMapControl(){
        //向地图中添加缩放控件
        var ctrl_nav = new BMap.NavigationControl({anchor:BMAP_ANCHOR_TOP_LEFT,type:BMAP_NAVIGATION_CONTROL_ZOOM});
        map.addControl(ctrl_nav);
        //向地图中添加缩略图控件
        var ctrl_ove = new BMap.OverviewMapControl({anchor:BMAP_ANCHOR_BOTTOM_RIGHT,isOpen:0});
        map.addControl(ctrl_ove);
        //向地图中添加比例尺控件
        var ctrl_sca = new BMap.ScaleControl({anchor:BMAP_ANCHOR_BOTTOM_LEFT});
        map.addControl(ctrl_sca);
    }

    //标注点数组
    var markerArr = [{title:"深圳市瑞云科技有限公司",content:"我的备注",point:"113.920892|22.519903",isOpen:0,icon:{w:23,h:25,l:46,t:21,x:9,lb:12}}
    ];
    //创建marker
    function addMarker(){
        for(var i=0;i<markerArr.length;i++){
            var json = markerArr[i];
            var p0 = json.point.split("|")[0];
            var p1 = json.point.split("|")[1];
            var point = new BMap.Point(p0,p1);
            var iconImg = createIcon(json.icon);
            var marker = new BMap.Marker(point,{icon:iconImg});
            var iw = createInfoWindow(i);
            var label = new BMap.Label(json.title,{"offset":new BMap.Size(json.icon.lb-json.icon.x+10,-20)});
            marker.setLabel(label);
            map.addOverlay(marker);
            label.setStyle({
                borderColor:"#808080",
                color:"#333",
                cursor:"pointer"
            });

            (function(){
                var index = i;
                var _iw = createInfoWindow(i);
                var _marker = marker;
                _marker.addEventListener("click",function(){
                    this.openInfoWindow(_iw);
                });
                _iw.addEventListener("open",function(){
                    _marker.getLabel().hide();
                })
                _iw.addEventListener("close",function(){
                    _marker.getLabel().show();
                })
                label.addEventListener("click",function(){
                    _marker.openInfoWindow(_iw);
                })
                if(!!json.isOpen){
                    label.hide();
                    _marker.openInfoWindow(_iw);
                }
            })()
        }
    }
    //创建InfoWindow
    function createInfoWindow(i){
        var json = markerArr[i];
        var iw = new BMap.InfoWindow("<b class='iw_poi_title' title='" + json.title + "'>" + json.title + "</b><div class='iw_poi_content'>"+json.content+"</div>");
        return iw;
    }
    //创建一个Icon
    //    function createIcon(json){
    //        var icon = new BMap.Icon("http://app.baidu.com/map/images/us_mk_icon.png", new BMap.Size(json.w,json.h),{imageOffset: new BMap.Size(-json.l,-json.t),infoWindowOffset:new BMap.Size(json.lb+5,1),offset:new BMap.Size(json.x,json.h)})
    ////        return icon;
    //    }

    initMap();//创建和初始化地图
</script>