<?php
$this->headTitle($this->headTitle);
$this->headMeta()
    ->appendName('description', $this->description)
    ->appendName('keywords', $this->keywords);
?>
<?php
$this->headScript()->prependFile($this->basePath('js/pages/scrolloverflow.min.js'));
$this->headScript()->prependFile($this->basePath('js/pages/jquery.fullPage.js'));
$this->headScript()->prependFile($this->basePath('js/pages/index/wow.min.js'));
?>

<style>

    /* Backgrounds will cover all the section
    * --------------------------------------- */
    #section0,
    #section1,
    #section2,
    #section3{
        background-size: cover;
        background-attachment: fixed;
    }

    /* Defining each sectino background and styles
    * --------------------------------------- */
    #section0{
        background-image: url("../img/case/case_bg.jpg");
        background-size: cover;
    }
    #section0 h1{
        top: 50%;
        transform: translateY(-50%);
        position: relative;
    }
    #section6{
        background-image: url("../img/case/duck.jpg");
        background-size: cover;
        background-position: center;
        /*padding: 6% 0 0 0;*/
    }
    #section1{
        background-image: url("../img/case/case_hublot.jpg");
        background-size: cover;
        background-position: center;
        /*padding: 6% 0 0 0;*/
    }
    #section2{
        background-image: url("../img/case/case_dsgl.jpg");
        /*padding: 6% 0 0 0;*/
    }
    #section3{
        background-image: url("../img/case/case_zl.jpg");
        /*padding: 6% 0 0 0;*/
    }
    #section4{
        background-image: url("../img/case/case_vivue.jpg");
        background-size: cover;
        background-position: center;
        /*padding: 6% 0 0 0;*/
    }

    #section3 h1{
        color: #000;
    }




    /* Bottom menu
    * --------------------------------------- */
    #infoMenu li a {
        color: #fff;
    }
</style>
<script type="text/javascript">
    $(document).ready(function() {
        $('#fullpage').fullpage({
            verticalCentered: false,

            //to avoid problems with css3 transforms and fixed elements in Chrome, as detailed here: https://github.com/alvarotrigo/fullPage.js/issues/208
            css3:false
        });
    });
    new WOW().init();
</script>
<div class="main-container" id="case-page" style="cursor: default">

    <div id="fullpage">
        <div class="section case-one" id="section0">
            <div class="container wow bounceInUp" data-wow-duration="1s" style=" position: relative; height: 100%">
                <div class="row case-first">
                    <div class="col-md-6 case-first-text" >
                        <img src="<?php echo $this->basePath('img/case/case_star.png')?>" class="star_img">
                        <div class="first-text">
                            <h3>瑞云客户如繁星般璀璨</h3>
                            <span>
                               瑞云的客户包括世界顶级动画电影制作工作室、特效工作室以及国内大部分主流动画制作公司，来自世界50个国家和地区，其中还包括奥斯卡奖得主。
                           </span>
                        </div>

                    </div>
                    <div class="col-md-6">&nbsp;</div>
                </div>
                <div class="row case-first-logo">
                    <div class="col-md-6 col-sm-6 col-xs-12 logo-first">
                        <img src="<?php echo $this->basePath('img/case/case_logo1.png')?>">
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-12 logo-first" >
                        <img src="<?php echo $this->basePath('img/case/case_logo2.png')?>">
                    </div>
                </div>
                <div class="row case-second-logo">
                    <div class="col-md-6 col-sm-6 col-xs-12 logo-first">
                        <img src="<?php echo $this->basePath('img/case/case_logo3.png')?>">
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-12 logo-first">
                        <img src="<?php echo $this->basePath('img/case/case_logo4.png')?>">
                    </div>
                </div>
                <i class="ic_pagearr"></i>
            </div>
        </div>
        <div class="section case-six" id="section6">
            <div class="container" style="height: 100%">
                <div class="row" style="height: 100%">
                    <div class="col-md-7 col-sm-5 col-xs-12" style="display: none">&nbsp;</div>
                    <div class="col-md-5 col-sm-5 col-xs-12 case-common-text" >
                        <div class="second-top">
                            <!--                        <div class="img-content"> <img src="--><?php //echo $this->basePath('img/case/case_add.png')?><!--" class="img-add"></div>-->
                            <h5>瑞云渲染案例</h5>
                            <span style="font-size: 30px;display: inline-block;line-height: 30px;font-weight: 700">DUCK DUCK GOOSE</span>
                                <h3> 妈妈咪鸭 </h3>
                            <span>国内首部全球同步发行的原创动画大电影<br>
                            2018年国内最高质量的3D动画电影</span>

                            <div class="second-bottom" >
                                <div class="row case-info-img">
                                </div>
                                <p>
                                    “《妈妈咪鸭》从创作伊始就是同一支团队的跨国协作，从艺术效果、故事到令人惊艳的动画制作，这一切都让我们无比自豪。中国南京和洛杉矶Culver城的原力动画成员们创作出了这样一部漂亮又丰富的电影，相信全世界的观众都会爱上它。”——原力动画CEO赵锐
                                </p>

                                <img src="<?php echo $this->basePath('img/case/case_d.png')?>" class="img-down">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="section case-second" id="section1">
            <div class="container" style="height: 100%">
                <div class="row" style="height: 100%">
                    <div class="col-md-7 col-sm-5 col-xs-12" style="display: none">&nbsp;</div>
                    <div class="col-md-5 col-sm-5 col-xs-12 case-common-text" >
                        <div class="second-top">
<!--                        <div class="img-content"> <img src="--><?php //echo $this->basePath('img/case/case_add.png')?><!--" class="img-add"></div>-->
                        <h5>瑞云渲染案例</h5>
                            <h3>哈布洛先生<br>
                                Mr. Hublot</h3>
                            <span>卢森堡3D动画短片，长11分钟，<br>
                            2014年第86届奥斯卡最佳动画短片奖。</span>

                            <div class="second-bottom">
                                <div class="row case-info-img">
                                    <div class="col-md-4 col-sm-4 col-xs-4">
                                        <img src="<?php echo $this->basePath('img/case/case_01.png')?>">
                                        <span>卢森堡3D
                                      动画短片</span>
                                    </div>
                                    <div class="col-md-4 col-sm-4 col-xs-4">
                                        <img src="<?php echo $this->basePath('img/case/case_02.png')?>">
                                        <span>短片时长<br>
                                 11分钟</span>
                                    </div>
                                    <div class="col-md-4 col-sm-4 col-xs-4">
                                        <img src="<?php echo $this->basePath('img/case/case_03.png')?>">
                                        <span> 第86届奥斯卡最佳动画短片奖</span>
                                    </div>
                                </div>
                                <p>
                                    “作为一家在法国的3D动画电影的小型工作室，我们需要大量的运算力来展现我们的创意，这需要比工作室多得多的电脑，在没有任何外界帮助下，计算机渲染这部分难以完成，最终我们找到了瑞云。”---短片导演 劳伦特维茨(Laurent Witz)
                                </p>

                                <img src="<?php echo $this->basePath('img/case/case_d.png')?>" class="img-down">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="section case-three" id="section2">
            <div class="container" style="height: 100%">
                <div class="row" style="height: 100%">
                    <div class="col-md-7 col-sm-5 col-xs-12" style="display: none">&nbsp;</div>
                    <div class="col-md-5 col-sm-5 col-xs-12 case-common-text" >
<!--                        <div class="img-content"> <img src="--><?php //echo $this->basePath('img/case/case_add.png')?><!--" class="img-add"></div>-->
                        <h5>瑞云渲染案例</h5>
                        <h3>西游记之<br>
                            大圣归来</h3>
                        <span>坚持严谨的态度和高质量的技术保障<br>
                            创下了近十亿的国产动画票房神话</span>
                        <div class="row case-info-img">
                            <div class="col-md-4 col-sm-4 col-xs-4" style="padding-left: 0px;">
                                <img src="<?php echo $this->basePath('img/case/case_04.png')?>">
                                <span>第30届中国电影
                                      金鸡奖最佳美术片</span>
                            </div>
                            <div class="col-md-4 col-sm-4 col-xs-4" style="padding-left: 0px;padding-right: 0px">
                                <img src="<?php echo $this->basePath('img/case/case_05.png')?>">
                                <span>第16届中国电影
                                 华表奖优秀故事片奖</span>
                            </div>
                            <div class="col-md-4 col-sm-4 col-xs-4">
                                &nbsp;
                            </div>
                        </div>
                        <p>
                            《大圣归来》是根据中国传统神话故事《西游记》进行拓展和演绎的3D动画电影，获得2015年第30届中国电影金鸡奖最佳美术片奖和第16届中国电影华表奖优秀故事片奖。
                        </p>

                        <img src="<?php echo $this->basePath('img/case/case_d.png')?>" class="img-down">

                    </div>
                </div>
            </div>
        </div>
        <div class="section case-four" id="section3">
            <div class="container" style="height: 100%">
                <div class="row" style="height: 100%">
                    <div class="col-md-7 col-sm-5 col-xs-12" style="display: none"></div>
                    <div class="col-md-5 col-sm-5 col-xs-12 case-common-text" >
<!--                        <img src="--><?php //echo $this->basePath('img/case/case_add.png')?><!--" class="img-add">-->
                        <h5>瑞云渲染案例</h5>
                        <h3>战狼Ⅱ</h3>
                        <span>国内重工业商业大片时代的开端<br>
                            刷新中国电影票房新纪录</span>
                        <div class="row case-info-img">
                            <div class="col-md-4 col-sm-4 col-xs-4">
                                <img src="<?php echo $this->basePath('img/case/case_06.png')?>">
                                <span>中国电影周金鹤
                                      奖最佳影片 </span>
                            </div>
                            <div class="col-md-4  col-sm-4 col-xs-4">
                                <img src="<?php echo $this->basePath('img/case/case_07.png')?>">
                                <span>“五个一工程”
                                 优秀作品奖</span>
                            </div>
                            <div class="col-md-4  col-sm-4 col-xs-4">
                                <img src="<?php echo $this->basePath('img/case/case_08.png')?>">
                                <span>中美电影节
                                 最佳电影</span>
                            </div>
                        </div>
                        <p>
                            上映首日破亿，96小时已破12亿，刷新了华语影史单日票房冠军记录，创下华语电影史“最快破10亿”票房新纪录。中国市场观影人次达1.4亿，跻身全球影史“单一市场观影人次”榜首。
                        </p>

                        <img src="<?php echo $this->basePath('img/case/case_d.png')?>" class="img-down">

                    </div>
                </div>
            </div></div>
        <div class="section case-five" id="section4">
            <div class="container" style="height: 100%">
                <div class="row" style="height: 100%">
                    <div class="col-md-7 col-sm-5 col-xs-12" style="display: none">&nbsp;</div>
                    <div class="col-md-5 col-sm-5 col-xs-12 case-common-text" >
<!--                        <div class="img-content"> <img src="--><?php //echo $this->basePath('img/case/case_add.png')?><!--" class="img-add"></div>-->
                        <h5>VIVUE审片合作案例</h5>
                        <h4>第八届中国国际新媒体短片节</h4>
                        <h3>国际评选委员会评审平台</h3>
                        <span>
                       新媒体短片节创每年都有上千部作品报名参与，冯小刚、陆川、陈可辛、蒋雯丽等行业大咖均担任过评委会主席。
                        </span>
                        <div class="row case-info-img">
                            <div class="col-md-4 col-sm-4 col-xs-4">
                                <img src="<?php echo $this->basePath('img/case/case_09.png')?>">
                                <span>金鹏奖<br>
                                        &nbsp;&nbsp;
                                    </span>
                            </div>
                            <div class="col-md-4  col-sm-4 col-xs-4">
                                <img src="<?php echo $this->basePath('img/case/case_010.png')?>">
                                <span>随时随地<br>
                                 高效审片</span>
                            </div>
                            <div class="col-md-4  col-sm-4 col-xs-4">
                                <img src="<?php echo $this->basePath('img/case/case_11.png')?>">
                                <span>精准评论<br>
                                 快速汇总</span>
                            </div>
                        </div>
                        <p>
                            VIVUE.io ，作为第八届中国国际新媒体短片节“终审合作平台”，提供了一个完美连接组委会和各国评委、不受时间地域限制、随时随地进行精确点评、自动汇总评分结果的高效审片协作平台。
                        </p>


                    </div>
                </div>
                <div class="page-footer" style="line-height: 0px">
                    <footer>
                        <div class="container foot">
                            <div class="row">
                                <div class="col-md-3 col-sm-3 col-xs-12"></div>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <div class="row font-talk" style="padding: 0 50px">
                                        <div class="col-md-3 col-sm-3 col-xs-3">
                                            <div class="wechatq">
                                                <img src="<?php echo $this->basePath('img/common/wechat_q.png')?>">
                                            </div>
                                            <a href="javascript:void(0)"  class="wechat"></a>
                                        </div>
                                        <div class="col-md-3 col-sm-3 col-xs-3">
                                            <a href="http://www.weibo.com/renderbus" class="weibo" target="_blank"></a>
                                        </div>
                                        <div class="col-md-3 col-sm-3 col-xs-3">
                                            <a href="https://www.facebook.com/rayvision.inc" class="facebook" target="_blank"></a>
                                        </div>
                                        <div class="col-md-3 col-sm-3 col-xs-3">
                                            <a href="http://www.linkedin.com/company/rayvision" class="linkedin" target="_blank"></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3 col-sm-3 col-xs-12"></div>
                            </div>
                            <div class="row bottom-link">
                                <div class="col-md-3 col-sm-3 col-xs-12"></div>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <ul>
                                        <li><a href="<?php echo $this->url('about'); ?>">关于瑞云</a> <span class="link-line"></span></li>
                                        <li><a href="http://www.renderbus.com/news/main" target="_blank">新闻中心</a><span class="link-line"></span></li>
                                        <li><a href="<?php echo $this->url('case'); ?>">成功案例</a><span class="link-line"></span></li>
                                        <li><a href="http://www.rayvision.com/en/about.html#about-bottom"">联系我们</a><span class="link-line"></span></li>
                                        <li><a href="<?php echo $this->url('join-us'); ?>">加入瑞云</a></li>
                                    </ul>
                                </div>
                                <div class="col-md-3 col-sm-3 col-xs-12"></div>
                            </div>
                            <p class="recording">
                                © 2017 深圳市瑞云科技有限公司 粤ICP备12028569号-2
                            </p>
                        </div>
                    </footer>

                </div>
            </div>
        </div>
    </div>

</div>

