<?php
$this->headScript()->prependFile($this->basePath('js/pages/index/scrollReveal.min.js'));
$this->headScript()->prependFile($this->basePath('js/pages/index/jquery.mousewheel.min.js'));
$this->headScript()->prependFile($this->basePath('js/pages/index/jquery.slimscroll.min.js'));
$this->headScript()->prependFile($this->basePath('js/pages/index/ddfullscreenslider.js'));
?>
<div class="main-container" id="case-page" >


    <section id="dowebok" class="dd_fullscreenslider">
        <div class="slidewrapper">
            <article class="slide case-one">
                <div class="container">
                     <div class="row case-first" data-scroll-reveal>
                  <div class="col-md-6 case-first-text">
                          <img src="<?php echo $this->basePath('img/case/case_star.png')?>" class="star_img">
                       <div class="first-text">
                           <h3>瑞云客户如繁星般璀璨</h3>
                           <span>
                               瑞云的客户包括世界顶级动画电影制作工作室、特效工作室以及国内大部分主流动画制作公司，来自世界40个国家和地区，其中还包括两位奥斯卡奖得主。
                           </span>
                       </div>

                  </div>
                  <div class="col-md-6">&nbsp;</div>
              </div>
                    <div class="row case-first-logo" data-scroll-reveal>
                        <div class="col-md-6 col-sm-6 col-xs-12 logo-first">
                            <img src="<?php echo $this->basePath('img/case/case_logo1.png')?>">
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-12" >
                            <img src="<?php echo $this->basePath('img/case/case_logo2.png')?>">
                        </div>
                    </div>
                    <div class="row case-second-logo" data-scroll-reveal>
                        <div class="col-md-6 col-sm-6 col-xs-12 logo-first">
                            <img src="<?php echo $this->basePath('img/case/case_logo3.png')?>">
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <img src="<?php echo $this->basePath('img/case/case_logo4.png')?>">
                        </div>
                    </div>
                </div>
            </article>

            <article class="slide case-second">
                <div class="container" style="height: 100%">
                    <div class="row" style="height: 100%">
                        <div class="col-md-7">&nbsp;</div>
                        <div class="col-md-5 case-common-text">
                            <div class="second-top">
                            <img src="<?php echo $this->basePath('img/case/case_add.png')?>" class="img-add">
                            <h5>瑞云渲染案例</h5>
                            <h3>哈布洛先生<br>
                                Mr. Hublot</h3>
                            <span>卢森堡3D动画短片，长11分钟，<br>
                            2014年第86届奥斯卡最佳动画短片奖。</span>

                            <div class="second-bottom">
                           <div class="row case-info-img">
                               <div class="col-md-3">
                                   <img src="<?php echo $this->basePath('img/case/case_01.png')?>">
                                   <span>卢森堡3D<br>
                                      动画短片</span>
                               </div>
                               <div class="col-md-3">
                                   <img src="<?php echo $this->basePath('img/case/case_02.png')?>">
                                  <span>短片时长<br>
                                 11分钟</span>
                               </div>
                               <div class="col-md-3">
                                   <img src="<?php echo $this->basePath('img/case/case_03.png')?>">
                                   <span> 第86届奥斯卡<br>
                                     最佳动画短片奖</span>
                               </div>
                           </div>
                            <p>
                                “作为一家在法国的３Ｄ动画电影的小型工作室，我们需要大量的运算力来展现我们的创意，这需要比工作室多得多的电脑，在没有任何外界帮助下，计算机渲染这部分难以完成，最终我们找到了瑞云。”---短片导演 劳伦特维茨(Laurent Witz)
                            </p>

                            <img src="<?php echo $this->basePath('img/case/case_d.png')?>" class="img-down">
                            </div>
                            </div>
                        </div>
                    </div>
                </div>

            </article>

            <article class="slide case-three">
                <div class="container" style="height: 100%">
                    <div class="row" style="height: 100%">
                        <div class="col-md-7">&nbsp;</div>
                        <div class="col-md-5 case-common-text" >
                            <img src="<?php echo $this->basePath('img/case/case_add.png')?>" class="img-add">
                            <h5>瑞云渲染案例</h5>
                            <h3>西游记之<br>
                                大圣归来</h3>
                            <span>坚持严谨的态度和高质量的技术保障<br>
                            创下了近十亿的国产动画票房神话</span>
                            <div class="row case-info-img">
                                <div class="col-md-3" style="padding-left: 0px;padding-right: 0px">
                                    <img src="<?php echo $this->basePath('img/case/case_03.png')?>">
                                    <span>第30届中国电影<br>
                                      金鸡奖最佳美术片</span>
                                </div>
                                <div class="col-md-3" style="padding-left: 0px;padding-right: 0px">
                                    <img src="<?php echo $this->basePath('img/case/case_04.png')?>">
                                    <span>第16届中国电影<br>
                                 华表奖优秀故事片奖</span>
                                </div>
                                <div class="col-md-3">
                                    &nbsp;
                                </div>
                                <div class="col-md-3">
                                    &nbsp;
                                </div>
                            </div>
                            <p>
                                《大圣归来》是根据中国传统神话故事《西游记》进行拓展和演绎的3D动画电影，获得2015年第30届中国电影金鸡奖最佳美术片奖和第16届中国电影华表奖优秀故事片奖。
                           </p>

                            <img src="<?php echo $this->basePath('img/case/case_d.png')?>" class="img-down">

                        </div>
                    </div>
                </div>
            </article>

            <article class="slide case-four">
                <div class="container" style="height: 100%">
                    <div class="row" style="height: 100%">
                        <div class="col-md-7">&nbsp;</div>
                        <div class="col-md-5 case-common-text" >
                            <img src="<?php echo $this->basePath('img/case/case_add.png')?>" class="img-add">
                            <h5>瑞云渲染案例</h5>
                            <h3>战狼Ⅱ</h3>
                            <span>国内重工业商业大片时代的开端<br>
                            刷新中国电影票房新纪录</span>
                            <div class="row case-info-img">
                                <div class="col-md-3 col-sm-3 col-xs-4">
                                    <img src="<?php echo $this->basePath('img/case/case_06.png')?>">
                                    <span>中国电影周金鹤<br>
                                      奖最佳影片 </span>
                                </div>
                                <div class="col-md-3  col-sm-3 col-xs-4">
                                    <img src="<?php echo $this->basePath('img/case/case_07.png')?>">
                                    <span>“五个一工程”<br>
                                 优秀作品奖</span>
                                </div>
                                <div class="col-md-3  col-sm-3 col-xs-4">
                                    <img src="<?php echo $this->basePath('img/case/case_08.png')?>">
                                    <span>中美电影节<br>
                                 最佳电影</span>
                                </div>
                                <div class="col-md-3  col-sm-3">
                                    &nbsp;
                                </div>
                            </div>
                            <p>
                                上映首日破亿，96小时已破12亿，刷新了华语影史单日票房冠军记录，创下华语电影史“最快破10亿”票房新纪录。中国市场观影人次达1.4亿，跻身全球影史“单一市场观影人次”榜首。
                          </p>

                            <img src="<?php echo $this->basePath('img/case/case_d.png')?>" class="img-down">

                        </div>
                    </div>
                </div>
            </article>

            <article class="slide case-five">
                <div class="container" style="height: 100%">
                    <div class="row" style="height: 100%">
                        <div class="col-md-7">&nbsp;</div>
                        <div class="col-md-5 case-common-text" >
                            <img src="<?php echo $this->basePath('img/case/case_add.png')?>" class="img-add">
                            <h5>VIVUE审片合作案例</h5>
                            <h4>第八届中国国际新媒体短片节</h4>
                            <h3>国际评选委员会评审平台</h3>
                            <span>
                                中国国际新媒体短片节创办于2010年，是目前中国唯一国家级、国际性短片节。每年都有上千部作品报名参与，冯小刚、陆川、陈可辛、蒋雯丽等行业大咖均担任过评委会主席，最高奖项“金鹏奖”备受学界业界关注。
                           </span>
                            <div class="row case-info-img">
                                <div class="col-md-3 col-sm-3 col-xs-4">
                                    <img src="<?php echo $this->basePath('img/case/case_09.png')?>">
                                    <span>金鹏奖<br>
                                        &nbsp;&nbsp;
                                    </span>
                                </div>
                                <div class="col-md-3  col-sm-3 col-xs-4">
                                    <img src="<?php echo $this->basePath('img/case/case_10.png')?>">
                                    <span>随时随地<br>
                                 高效审片</span>
                                </div>
                                <div class="col-md-3  col-sm-3 col-xs-4">
                                    <img src="<?php echo $this->basePath('img/case/case_11.png')?>">
                                    <span>精准评论<br>
                                 快速汇总</span>
                                </div>
                                <div class="col-md-3  col-sm-3">
                                    &nbsp;
                                </div>
                            </div>
                            <p>
                                VIVUE.io ，作为第八届中国国际新媒体短片节“终审合作平台”，提供了一个完美连接组委会和各国评委、不受时间地域限制、随时随地进行精确点评、自动汇总评分结果的高效审片协作平台。
                           </p>

                            <img src="<?php echo $this->basePath('img/case/case_d.png')?>" class="img-down">

                        </div>
                    </div>
                    <div class="page-footer" style="line-height: 0px">
                        <footer>
                            <div class="container foot">
                                <div class="row">
                                    <div class="col-md-3 col-sm-3 col-xs-12"></div>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <div class="row font-talk" style="padding: 0 50px">
                                            <div class="col-md-3 col-sm-3 col-xs-3">
                                                <div class="wechatq">
                                                    <img src="<?php echo $this->basePath('img/common/wechat_q.png')?>">
                                                </div>
                                                <a href="" class="wechat"></a>
                                            </div>
                                            <div class="col-md-3 col-sm-3 col-xs-3">
                                                <a href="" class="weibo"></a>
                                            </div>
                                            <div class="col-md-3 col-sm-3 col-xs-3">
                                                <a href="" class="facebook"></a>
                                            </div>
                                            <div class="col-md-3 col-sm-3 col-xs-3">
                                                <a href="" class="linkedin"></a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3 col-sm-3 col-xs-12"></div>
                                </div>
                                <div class="row bottom-link">
                                    <div class="col-md-3 col-sm-3 col-xs-12"></div>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <ul>
                                            <li><a href="">关于瑞云</a> <span class="link-line"></span></li>
                                            <li><a href="">新闻中心</a><span class="link-line"></span></li>
                                            <li><a href="">成功案例</a><span class="link-line"></span></li>
                                            <li><a href="">联系我们</a><span class="link-line"></span></li>
                                            <li><a href="">加入瑞云</a></li>
                                        </ul>
                                    </div>
                                    <div class="col-md-3 col-sm-3 col-xs-12"></div>
                                </div>
                                <p class="recording">
                                    © 2017 深圳市瑞云科技有限公司 粤ICP备12028569号-2
                                </p>
                            </div>
                        </footer>

                    </div>
                </div>
            </article>
        </div>
    </section>

</div>

<script>
    var fss;
    $(function() {
        fss = new ddfullscreenslider({
            sliderid: 'dowebok',
            addHash: false
        });
    });
    window.scrollReveal = new scrollReveal();
    $("#dowebok").mousewheel(function () {
        var selectedParent1 = $("#selected1").parent();
        var selectedParent2 = $("#selected2").parent();
        var selectedParent3 = $("#selected3").parent();
        var selectedParent4 = $("#selected4").parent();
        var selectedParent5 = $("#selected5").parent();
        if(selectedParent1.hasClass("selected")){
            $(".second-top").css({"margin-top":"0px","opacity":"1"});
//            $(".second-bottom").css({"margin-top":"0px","opacity":"1"});
//             $(".second-bottom")
//            setTimeout(function () {
//                $(".second-bottom").css({"margin-top":"0px","opacity":"1"});
//            },50)
        }

        if(selectedParent2.hasClass("selected")){

        }
        if(selectedParent3.hasClass("selected")){

        }
    })
</script>