<?php
$this->headTitle($this->headTitle);
$this->headMeta()
    ->appendName('description', $this->description)
    ->appendName('keywords', $this->keywords);
?>
<?php
$this->headScript()->prependFile($this->basePath('js/pages/index/scrollReveal.min.js'));
$this->headScript()->prependFile($this->basePath('js/pages/index/jquery.mousewheel.min.js'));
$this->headScript()->prependFile($this->basePath('js/pages/index/jquery.slimscroll.min.js'));
$this->headScript()->prependFile($this->basePath('js/pages/index/ddfullscreenslider.js'));
?>
<div class="main-container" id="index-page" >
    <section id="dowebok" class="dd_fullscreenslider">
        <div class="slidewrapper">
            <article class="slide" id="rayvision">
                <div class="container" style="width: 1200px;  height: 100%; margin: 0 auto;">
                <div class="first">
                        <div class="first_center" data-scroll-reveal> </div>
                    <div class="first_center_text" data-scroll-reveal>
                            <p>
                                RAYVISION VISUAL<br/>  CLOUD COMPUTING PLATFORM
                            </p>
                            <h3>RAYVISION</br>
                                视觉<span>云计算</span></br>服务平台</h3>
                            <span class="first_text">超85%CG工作室的选择</span>
                        </div>
                </div>
                </div>
                    <div id="container">
                        <video id="background_video" loop muted></video>
                        <div id="video_cover"></div>
                        <div id="overlay"></div>
                        <div id="video_controls">
                                      <span id="play">
                <!--                        <img src="play.png">-->
                                      </span>
                            <span id="pause">
                <!--                        <img src="pause.png">-->
                                      </span>
                        </div>

                    </div>
                <a href="javascript:;" class="ic_pagearr"></a>
            </article>

            <article class="slide second" id="rayvision2">
          <div class="container" id="second">
                  <div class="second_text" >
                      <img src="<?php echo $this->basePath('img/index/Render.png')?>">
             <h3>全球领先的云渲染平台</h3>
              <p>7天24小时服务 · 奥斯卡专业服务团队 · 随时可用 · 好莱坞级安全</p>
              <p>影视 · 动画 · 效果图 · 一站渲染</p>
              <a href="http://www.renderbus.com/" target="_blank">访问Renderbus官网</a>
              </div>
            <div class="second_img">
                <ul>
                    <li class="second_one">
                        <a class="second_img1"></a>
                        <div class="second_img1_info">
                            <p>创下近十亿的国产动画票房神话</p>
                        </div>
                    </li>
                    <li class="second_two"><a class="second_img2"></a>
                        <div class="second_img2_info">
                            <p>刷新中国电影票房新纪录</p>
                        </div>
                    </li>
                    <li class="second_three"><a class="second_img3"></a>
                        <div class="second_img3_info">
                            <p>荣获第86届奥斯卡最佳动画短片</p>
                        </div>
                    </li>
                </ul>
            </div>


          </div>
            </article>

            <article class="slide three"id="rayvision3">
                <div class="container" id="three">
                    <div class="three_text">
                        <img src="<?php echo $this->basePath('img/index/raysync.png')?>">
                        <h3>镭速企业级大文件传输</h3>
                        <p>完美解决客户跨国传输、远距离传输、大文件传输等问题</p>
                        <a href="https://www.raysync.io/" target="_blank">访问镭速官网</a>
                    </div>
                </div>

            </article>

            <article class="slide four" id="rayvision4">
              <div class="container" >
                  <div class="row">
                      <div class="col-md-3 col-sm-12 col-xs-12">&nbsp;</div>
                      <div class="col-md-6 col-sm-12 col-xs-12" style="padding: 0px" id="four-text">
                          <div class="four_text">
                              <img src="<?php echo $this->basePath('img/index/vivue_logo_w.png')?>">
                              <h3>更高效的审片协作平台</h3>
                              <p>随时随地解决视频上传 评审 团队协作问题</p>
                              <a href="https://www.vivue.io/" target="_blank">访问VIVUE官网</a>
                          </div>
                      </div>
                      <div class="col-md-3 col-sm-12 col-xs-12">&nbsp;</div>
                  </div>

                  <div class="page-footer" style="line-height: 0px;margin: 0 auto">
                      <footer>
                          <div class="foot">
                              <div class="row">
                                  <div class="col-md-3 col-sm-3 col-xs-12"></div>
                                  <div class="col-md-6 col-sm-6 col-xs-12">
                                      <div class="row font-talk" style="padding: 0 50px">
                                          <div class="col-md-3 col-sm-3 col-xs-3">
                                              <div class="wechatq">
                                                  <img src="<?php echo $this->basePath('img/common/wechat_q.png')?>">
                                              </div>
                                              <a href="javascript:void(0)"  class="wechat"></a>
                                          </div>
                                          <div class="col-md-3 col-sm-3 col-xs-3">
                                              <a href="http://www.weibo.com/renderbus" class="weibo" target="_blank"></a>
                                          </div>
                                          <div class="col-md-3 col-sm-3 col-xs-3">
                                              <a href="https://www.facebook.com/rayvision.inc" class="facebook" target="_blank"></a>
                                          </div>
                                          <div class="col-md-3 col-sm-3 col-xs-3">
                                              <a href="http://www.linkedin.com/company/rayvision" class="linkedin" target="_blank"></a>
                                          </div>
                                      </div>
                                  </div>
                                  <div class="col-md-3 col-sm-3 col-xs-12"></div>
                              </div>
                              <div class="row bottom-link">
                                  <div class="col-md-3 col-sm-3 col-xs-12"></div>
                                  <div class="col-md-6 col-sm-6 col-xs-12">
                                      <ul>
                                          <li><a href="<?php echo $this->url('about'); ?>">关于瑞云</a> <span class="link-line"></span></li>
                                          <li><a href="http://www.renderbus.com/news/main" target="_blank">新闻中心</a><span class="link-line"></span></li>
                                          <li><a href="<?php echo $this->url('case'); ?>">成功案例</a><span class="link-line"></span></li>
                                          <li><a href="http://www.rayvision.com/about.html#about-bottom"">联系我们</a><span class="link-line"></span></li>
                                          <li><a href="<?php echo $this->url('join-us'); ?>">加入瑞云</a></li>
                                      </ul>
                                  </div>
                                  <div class="col-md-3 col-sm-3 col-xs-12"></div>
                              </div>
                              <p class="recording">
                                  © 2017 深圳市瑞云科技有限公司 粤ICP备12028569号-2
                              </p>
                          </div>
                      </footer>

                  </div>
              </div>

            </article>
        </div>
    </section>
</div>
<script>
    (function () {

        if ( typeof window.CustomEvent === "function" ) return false;

        function CustomEvent ( event, params ) {
            params = params || { bubbles: false, cancelable: false, detail: undefined };
            var evt = document.createEvent( 'CustomEvent' );
            evt.initCustomEvent( event, params.bubbles, params.cancelable, params.detail );
            return evt;
        }

        CustomEvent.prototype = window.Event.prototype;

        window.CustomEvent = CustomEvent;
    })();
    var fss;
    $(function() {
        fss = new ddfullscreenslider({
            sliderid: 'dowebok',
            addHash: false
        });
    });
    window.scrollReveal = new scrollReveal();

//    判断浏览器型号,如果为ie为10以上执行正常文字出现，如果不是强制让文字出现
//    function getBrowser(getVersion)
//    {
//        //注意关键字大小写
//        var ua_str = navigator.userAgent.toLowerCase(), ie_Tridents, trident, match_str, ie_aer_rv, browser_chi_Type;
//
//        //判断IE 浏览器,
//        //blog: http://blog.csdn.net/aerchi/article/details/51697592
//        if("ActiveXObject" in self){
//            // ie_aer_rv:  指示IE 的版本.
//            // It can be affected by the current document mode of IE.
//            ie_aer_rv= (match_str = ua_str.match(/msie ([\d.]+)/)) ?match_str[1] :
//                (match_str = ua_str.match(/rv:([\d.]+)/)) ?match_str[1] : 0;
//            console.log("ie_aer_rv"+ie_aer_rv);
//            console.log("match_str"+match_str)
//            // ie: Indicate the really version of current IE browser.
//            ie_Tridents = {"trident/7.0": 11, "trident/6.0": 10, "trident/5.0": 9, "trident/4.0": 8};
//            //匹配 ie8, ie11, edge
//            trident = (match_str = ua_str.match(/(trident\/[\d.]+|edge\/[\d.]+)/)) ?match_str[1] : undefined;
//            console.log("trident"+trident)
//            browser_chi_Type = (ie_Tridents[trident] || ie_aer_rv) > 0 ? "ie" : undefined;
//            console.log("ie_Tridents[trident] "+ie_Tridents[trident] );
//            console.log("browser_chi_Type "+browser_chi_Type );
//        }else{
//            //判断 windows edge 浏览器
//            // match_str[1]: 返回浏览器及版本号,如: "edge/13.10586"
//            // match_str[1]: 返回版本号,如: "edge"
//
//            //若要返回 "edge" 请把下行的 "ie" 换成 "edge"。 注意引号及冒号是英文状态下输入的
//            browser_chi_Type = (match_str = ua_str.match(/edge\/([\d.]+)/)) ? "ie" :
//                //判断firefox 浏览器
//                (match_str = ua_str.match(/firefox\/([\d.]+)/)) ? "firefox" :
//                    //判断chrome 浏览器
//                    (match_str = ua_str.match(/chrome\/([\d.]+)/)) ? "chrome" :
//                        //判断opera 浏览器
//                        (match_str = ua_str.match(/opera.([\d.]+)/)) ? "opera" :
//                            //判断safari 浏览器
//                            (match_str = ua_str.match(/version\/([\d.]+).*safari/)) ? "safari" : undefined;
//        }
//        //返回浏览器类型和版本号
//
//        var verNum, verStr;
//        var BrowserResulte = new Array();
//        verNum = trident && ie_Tridents[trident] ? ie_Tridents[trident] : match_str[1];
//        BrowserResulte[0] = verNum;
//        verStr = (getVersion != undefined) ? browser_chi_Type+"/"+verNum : browser_chi_Type;
//        BrowserResulte[1] = verStr;
//        return BrowserResulte;
//    }
//    var Browser = getBrowser();

//    鼠标滚动动画出现事件
    if(document.attachEvent){
//        if(10<Browser[0]&&Browser[1]=='ie'){
//            console.log("dddd1");
//            document.attachEvent('custSlideTo', function (event) {
//                console.log("dddd2");
//                console.info('kitsch,event.detail.delta',event.detail.delta)
//                var delta = event.detail.delta
//                var selectedParent1 = $("#selected1").parent();
//                var selectedParent2 = $("#selected2").parent();
//                var selectedParent3 = $("#selected3").parent();
//                var selectedParent4 = $("#selected4").parent();
//                if(delta < 0){
//                    if(selectedParent1.hasClass("selected")){
////                console.info('kitsch:', '1')
//                        $("#second").css({"margin-top":"0px","opacity":"1"})
//                    }
//                    if(selectedParent2.hasClass("selected")){
//                        $("#three").css({"margin-top":"0px","opacity":"1"})
////                console.info('kitsch:', '2')
//                    }
//                    if(selectedParent3.hasClass("selected")){
//                        $("#four-text").css({"margin-top":"0px","opacity":"1"})
//                        $(".page-footer").css({"bottom":"0px","opacity":"1"})
////                        $(".page-footer").css({"position":"absolute"})
//
////                console.info('kitsch:', '3')
//                    }
//                }
//                if(delta > 0){
//                    if(selectedParent3.hasClass("selected")){
//                        $("#second").css({"margin-top":"0px","opacity":"1"})
//                    }
//                    if(selectedParent4.hasClass("selected")){
//                        $("#three").css({"margin-top":"0px","opacity":"1"})
//                    }
//                }
//            })
//        }else{
//            console.log("dddd3");
            $("#second").css({"margin-top":"0px","opacity":"1"})
            $("#three").css({"margin-top":"0px","opacity":"1"})
            $("#four-text").css({"margin-top":"0px","opacity":"1"})
            $(".page-footer").css({"bottom":"0px","opacity":"1"})
//            $(".page-footer").css({"position":"relative"})
//        }
    }else {
        document.addEventListener('custSlideTo', function (event) {
            console.info('kitsch,event.detail.delta', event.detail.delta)
            var delta = event.detail.delta
            var selectedParent1 = $("#selected1").parent();
            var selectedParent2 = $("#selected2").parent();
            var selectedParent3 = $("#selected3").parent();
            var selectedParent4 = $("#selected4").parent();
            if (delta < 0) {
                if (selectedParent1.hasClass("selected")) {
//                console.info('kitsch:', '1')
                    $("#second").css({"margin-top": "0px", "opacity": "1"})
                }
                if (selectedParent2.hasClass("selected")) {
                    $("#three").css({"margin-top": "0px", "opacity": "1"})
//                console.info('kitsch:', '2')
                }
                if (selectedParent3.hasClass("selected")) {
                    $("#four-text").css({"margin-top": "0px", "opacity": "1"})
                    $(".page-footer").css({"bottom": "0px", "opacity": "1"})
//                console.info('kitsch:', '3')
                }
            }
            if (delta > 0) {
                if (selectedParent3.hasClass("selected")) {
                    $("#second").css({"margin-top": "0px", "opacity": "1"})
                }
                if (selectedParent4.hasClass("selected")) {
                    $("#three").css({"margin-top": "0px", "opacity": "1"})
                }
            }
        })}
    //键盘事件
    $(document).on('keyup',function (e) {
      var keyCode = e.keyCode;
      console.log(keyCode);
        var selectedParent1 = $("#selected1").parent();
        var selectedParent2 = $("#selected2").parent();
        var selectedParent3 = $("#selected3").parent();
        var selectedParent4 = $("#selected4").parent();
      if(keyCode === 40) {
          if (selectedParent1.hasClass("selected")) {
              $("#second").css({"margin-top": "0px", "opacity": "1"})
          }
          if (selectedParent2.hasClass("selected")) {
              $("#three").css({"margin-top": "0px", "opacity": "1"})
          }
          if (selectedParent3.hasClass("selected")) {
              $("#four-text").css({"margin-top": "0px", "opacity": "1"})
              $(".page-footer").css({"bottom": "0px", "opacity": "1"})
          }
      }
      if(keyCode === 38) {
          if (selectedParent3.hasClass("selected")) {
              $("#second").css({"margin-top": "0px", "opacity": "1"})
          }
          if (selectedParent4.hasClass("selected")) {
              $("#three").css({"margin-top": "0px", "opacity": "1"})
          }
      }


    });


</script>
<?php
$this->inlineScript()->appendFile($this->basePath('js/pages/index/bideo.js'));
$this->inlineScript()->appendFile($this->basePath('js/pages/index/main.js'));
?>


