<?php
$this->headScript()->prependFile($this->basePath('js/pages/index/scrollReveal.min.js'));
$this->headScript()->prependFile($this->basePath('js/pages/index/jquery.mousewheel.min.js'));
$this->headScript()->prependFile($this->basePath('js/pages/index/jquery.slimscroll.min.js'));
$this->headScript()->prependFile($this->basePath('js/pages/index/ddfullscreenslider.js'));
?>
<div class="main-container" id="index-page" >
    <section id="dowebok" class="dd_fullscreenslider">
        <div class="slidewrapper">
            <article class="slide" id="rayvision">
                <div class="container">
                <div class="row first">
                    <div class="col-md-5 col-sm-4 col-xs-3"> &nbsp;</div>
                    <div class="col-md-4 col-sm-5 col-xs-5">
                        <div class="first_center" data-scroll-reveal>
                            <p>
                                THE MOST USER-FRIENDLY VISUAL<br/>
                                CLOUD COMPUTING PLATFORM
                            </p>
                            <h3>最<span>贴近</span>用户的</br>
                                视觉<span>云计算</span></br>服务平台</h3>
                            <span class="first_text">超85%CG工作室的选择</span>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-4">&nbsp;</div>
                </div>
                </div>
                    <div id="container">
                        <video id="background_video" loop muted></video>
                        <div id="video_cover"></div>
                        <div id="overlay"></div>
                        <div id="video_controls">
                                      <span id="play">
                <!--                        <img src="play.png">-->
                                      </span>
                            <span id="pause">
                <!--                        <img src="pause.png">-->
                                      </span>
                        </div>

                    </div>
                <a href="javascript:;" class="ic_pagearr"></a>
            </article>

            <article class="slide second" id="rayvision2">
          <div class="container" id="second">
                  <div class="second_text" >
                      <img src="<?php echo $this->basePath('img/index/Render.png')?>">
             <h3>全球领先的云渲染平台</h3>
              <p>7天24小时服务 · 奥斯卡专业服务团队 · 随时可用 · 好莱坞级安全</p>
              <p>影视 · 动画 · 效果图 · 一站渲染</p>
              <a>了解更多</a>
              </div>
            <div class="second_img">
                <ul>
                    <li class="second_one">
                        <a class="second_img1"></a>
                        <div class="second_img1_info">
                            <p>荣获第86届奥斯卡最佳动画短片</p>
                        </div>
                    </li>
                    <li class="second_two"><a class="second_img2"></a>
                        <div class="second_img2_info">
                            <p>荣获第86届奥斯卡最佳动画短片</p>
                        </div>
                    </li>
                    <li class="second_three"><a class="second_img3"></a>
                        <div class="second_img3_info">
                            <p>荣获第86届奥斯卡最佳动画短片</p>
                        </div>
                    </li>
                </ul>
            </div>


          </div>
            </article>

            <article class="slide three"id="rayvision3">
                <div class="container" id="three">
                    <div class="three_text">
                        <img src="<?php echo $this->basePath('img/index/raysync.png')?>">
                        <h3>镭速企业级大文件传输</h3>
                        <p>完美解决客户跨国传输、远距离传输、大文件传输等问题</p>
                        <a>了解更多</a>
                    </div>
                </div>

            </article>

            <article class="slide four" id="rayvision4">
              <div class="container" >
                  <div class="row">
                      <div class="col-md-3 col-sm-12 col-xs-12">&nbsp;</div>
                      <div class="col-md-6 col-sm-12 col-xs-12" style="padding: 0px" id="four-text">
                          <div class="four_text">
                              <img src="<?php echo $this->basePath('img/index/vivue_logo_w.png')?>">
                              <h3>更高效的审片协作平台</h3>
                              <p>随时随地解决视频上传 评审 团队协作问题</p>
                              <a>了解更多</a>
                          </div>
                      </div>
                      <div class="col-md-3 col-sm-12 col-xs-12">&nbsp;</div>
                  </div>

                  <div class="page-footer" style="line-height: 0px">
                      <footer>
                          <div class="container foot">
                              <div class="row">
                                  <div class="col-md-3 col-sm-3 col-xs-12"></div>
                                  <div class="col-md-6 col-sm-6 col-xs-12">
                                      <div class="row font-talk" style="padding: 0 50px">
                                          <div class="col-md-3 col-sm-3 col-xs-3">
                                              <div class="wechatq">
                                                  <img src="<?php echo $this->basePath('img/common/wechat_q.png')?>">
                                              </div>
                                              <a href="" class="wechat"></a>
                                          </div>
                                          <div class="col-md-3 col-sm-3 col-xs-3">
                                              <a href="" class="weibo"></a>
                                          </div>
                                          <div class="col-md-3 col-sm-3 col-xs-3">
                                              <a href="" class="facebook"></a>
                                          </div>
                                          <div class="col-md-3 col-sm-3 col-xs-3">
                                              <a href="" class="linkedin"></a>
                                          </div>
                                      </div>
                                  </div>
                                  <div class="col-md-3 col-sm-3 col-xs-12"></div>
                              </div>
                              <div class="row bottom-link">
                                  <div class="col-md-3 col-sm-3 col-xs-12"></div>
                                  <div class="col-md-6 col-sm-6 col-xs-12">
                                      <ul>
                                          <li><a href="">关于瑞云</a> <span class="link-line"></span></li>
                                          <li><a href="">新闻中心</a><span class="link-line"></span></li>
                                          <li><a href="">成功案例</a><span class="link-line"></span></li>
                                          <li><a href="">联系我们</a><span class="link-line"></span></li>
                                          <li><a href="">加入瑞云</a></li>
                                      </ul>
                                  </div>
                                  <div class="col-md-3 col-sm-3 col-xs-12"></div>
                              </div>
                              <p class="recording">
                                  © 2017 深圳市瑞云科技有限公司 粤ICP备12028569号-2
                              </p>
                          </div>
                      </footer>

                  </div>
              </div>
            </article>
        </div>
    </section>
</div>

<script>
    var fss;
    $(function() {
        fss = new ddfullscreenslider({
            sliderid: 'dowebok',
            addHash: false
        });
    });
    window.scrollReveal = new scrollReveal();

//    自动载入动画出现事件
//    var selectedParent2 = $("#selected2").parent();
//    if(selectedParent2.hasClass("selected")){
//        $("#second").css({"margin-top":"0px","opacity":"1"})
//    }


//    鼠标滚动动画出现事件
$("#dowebok").mousewheel(function () {
    var selectedParent1 = $("#selected1").parent();
    var selectedParent2 = $("#selected2").parent();
    var selectedParent3 = $("#selected3").parent();
    var selectedParent4 = $("#selected4").parent();
    if(selectedParent1.hasClass("selected")){
     $("#second").css({"margin-top":"0px","opacity":"1"})
    }
    if(selectedParent2.hasClass("selected")){
        $("#three").css({"margin-top":"0px","opacity":"1"})
    }
    if(selectedParent3.hasClass("selected")){
        $("#four-text").css({"margin-top":"0px","opacity":"1"})
        $(".page-footer").css({"bottom":"0px","opacity":"1"})
    }
})

// 键盘上下事件
    $(document).on('keyup',function () {
        var selectedParent1 = $("#selected1").parent();
        var selectedParent2 = $("#selected2").parent();
        var selectedParent3 = $("#selected3").parent();
        var selectedParent4 = $("#selected4").parent();
        if(selectedParent1.hasClass("selected")){
            $("#second").css({"margin-top":"0px","opacity":"1"})
        }
        if(selectedParent2.hasClass("selected")){
            $("#three").css({"margin-top":"0px","opacity":"1"})
        }
        if(selectedParent3.hasClass("selected")){
            $("#four-text").css({"margin-top":"0px","opacity":"1"})
            $(".page-footer").css({"bottom":"0px","opacity":"1"})
        }
    });


</script>
<?php
$this->inlineScript()->appendFile($this->basePath('js/pages/index/bideo.js'));
$this->inlineScript()->appendFile($this->basePath('js/pages/index/main.js'));
?>


