<?php
$this->headTitle($this->headTitle);
$this->headMeta()
    ->appendName('description', $this->description)
    ->appendName('keywords', $this->keywords);
?>
<div class="main-container" id="join-us">
    <!--网站页眉-中文-->

    <!--网站banner-中文-->
    <div class="main-banner">
        <!--banner背景图-->
        <img src="<?php echo $this->basePath('img/join-us/hr_01.jpg')?>" class="img-responsive banner-bg" alt="renderfarm" />
        <!--banner文字内容-->
        <div class="banner-content">
            <div class="content-div">
                <p class=""><span class="company-recruit">欢迎来到瑞云</span><span class="company-recruit-span">伐木累</span></p>
                <p class="company-recruit-en">Welcome to RAYVISION Family</p>
<!--                <span class="company-recruit-des">好看的皮囊千篇一律，有趣的灵魂独一无二<br>世界那么大，你不来怎知你有趣</span>-->
            </div>
        </div>
    </div>
    <!--网站banner-中文-end-->

    <!--网站主体内容-中文-->
    <div class="main-content" id="main-content">

        <!--who are we-->
        <div class="content-intro width-responsive row">
            <div class="col-xs-12 col-sm-6 col-md-6 img-content" style="padding-left: 0px;padding-right: 0px; height: 100%">
                <img src="<?php echo $this->basePath('img/join-us/hr_02.png')?>" class="img-responsive intro-image" alt="rayvision" style="height: 100%" />
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6">
                <div class="intro-text">
                    <p class="title-p">Who are we?</p>
                    <h2 class="title-h2">我们是</h2>
                    <p class="intro-text-p">我们是全球最大的云渲染平台之一</p>
                    <p class="intro-text-p">我们是“中国自助式云渲染”的开创者</p>
                    <p class="intro-text-p">我们是阿里云视觉云计算全球战略合作伙伴</p>
                    <p class="intro-text-p">我们是奥斯卡获奖作品的幕后英雄</p>
                    <p class="intro-text-p">我们汇集了来自全球顶尖电影制作公司从业经验精英的CG的团队</p>
                    <p class="intro-text-p">我们拥有领先的数据传输核心技术—镭速（Raysync）传输引擎</p>
                    <p class="intro-text-p">更高效的VIVUE审片协作平台</p>
                    <p class="intro-text-p">我们驱动着影视、特效、建筑、设计等行业的发展</p>
                </div>
            </div>

        </div>
        <!--who are we-end-->

        <!--what we do-->
        <div class="content-work row">
            <div class="content-work-right">
                <div class="work-text">
                    <p class="title-p">How we work？</p>
                    <h2 class="title-h2">我们的工作模式</h2>
                    <p class="intro-text-p">对公司，我们绝对热爱</p>
                    <p class="intro-text-p">对工作，我们十分严谨</p>
                    <p class="intro-text-p">对产品，我们足够专业</p>
                    <p class="intro-text-p">对于玩，我们活力十足</p>
                    <p class="intro-text-p">我们是一群搞得定工作，稳得住客户，</p>
                    <p class="intro-text-p">又热得了场子的高颜值年轻团队！</p>
                </div>
            </div>
            <div class="content-work-left">
                <img src="<?php echo $this->basePath('img/join-us/hr_03.png')?>" class="work-image" alt="rayvision" />
            </div>

        </div>
        <!--what we do-end-->

        <!--who we want-->
        <div class="content-want width-responsive row">
            <div class="col-xs-12 col-sm-6 col-md-6">
                <img src="<?php echo $this->basePath('img/join-us/qrcode.jpg')?>" class="img-responsive want-image" alt="rayvision" />
                <p class="intro-text-p attention-ray">扫一扫 马上关注瑞云微信公众号</p>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6">
                <div class="want-text">
                    <p class="title-p">Who we want?</p>
                    <h2 class="title-h2">现在我们需要</h2>
                    <p class="intro-text-p">不怕你有想法，就怕你没创意</p>
                    <p class="intro-text-p">不怕你起点低，就怕你不努力</p>
                    <p class="intro-text-p">不怕你不了解影视行业，就怕你不愿意学习</p>
                    <p class="intro-text-p">不怕你是处女座，就怕你没有追求极致完美的决心</p>
                    <p class="intro-text-p">最好你还眼光独到有远见</p>
                    <p class="intro-text-p">茫茫人海中一眼就能看出瑞云是你的Mr. Right！</p>
                </div>
            </div>
        </div>
        <!--who we want-end-->

        <!--what will you get-->
        <div class="content-get">
            <div class="width-responsive2 row">
                <h2 class="title-h2 h2-exp">除此之外，你还得</h2>

                <!--left-->
                <div class="content-recruit  col-xs-12 col-sm-6 col-md-6">
                    <div>
                        <img src="<?php echo $this->basePath('img/join-us/recruit1.png')?>" class="recruit-img">
                    </div>
                    <div class="skill-content">
                        <p class="skill">——是美拍达人、修图高手</p>
                        <span class="skill-des">对美颜相机、FaceU、vsco、Mix等熟练度达到大师级别，不然每年一次的公司旅游，自拍都拍不好你怪谁？</span>
                    </div>
                </div>
                <div class="content-recruit col-xs-12 col-sm-6 col-md-6">
                    <div>
                        <img src="<?php echo $this->basePath('img/join-us/recruit2.png')?>" class="recruit-img">
                    </div>
                    <div class="skill-content">
                        <p class="skill">——要有一颗吃货的心</p>
                        <span class="skill-des">
                            毕竟每周一次的茶话会、员工生日会上的蛋糕甜点、水果饮品、佳节好礼需要你消灭。对了，每个月你还有固定的团建费，跟部门小伙伴去happy吧！
                        </span>
                    </div>
                </div>
                <div class="content-recruit col-xs-12 col-sm-6 col-md-6">
                    <div>
                        <img src="<?php echo $this->basePath('img/join-us/recruit3.png')?>" class="recruit-img">
                    </div>
                    <div class="skill-content">
                        <p class="skill">——必须是个合群的人</p>
                        <span class="skill-des">不然遇到每月一次的篮球同好会、乒乓球同好会、羽毛球同好会、游泳同好会、王者荣耀同好会……的时候，你只能孤独寂寞冷！</span>
                    </div>
                </div>
                <div class="content-recruit col-xs-12 col-sm-6 col-md-6">
                    <div>
                        <img src="<?php echo $this->basePath('img/join-us/recruit4.png')?>" class="recruit-img">
                    </div>
                    <div class="skill-content">
                        <p class="skill">——保持爱学习的态度</p>
                        <span class="skill-des">
                           不定期的培训会，交流会，部门商讨会……帮助你了解行业知识，为你解答工作上的种种疑惑！
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <!--what you will get-end-->

        <!--来到瑞云这些全都有-->
        <div class="content-welfare">
            <p class="welfare-import">最重要的一点</p>
            <h3>你在做自己热爱并且擅长的事情，你将扮演一个无可替代的角色！</h3>
            <span >如果很凑巧你跟我们是同类人，不妨把你的简历投过来，让我们看看你有多有趣？</span>
            <span>毕竟好看的皮囊千篇一律，有趣的灵魂只你一个。</span>
            <h4 class="onlineput">网络投递简历</h4>
            <div class="welfare-btn">
                <ul class="submit-resume">
                    <li class="submit-resume-li"><a href="mailto:hr@rayvision.com" class="resume-href" title="hr@rayvision.com">投递简历</a></li>
                    <li class="submit-resume-li"><a href="http://search.51job.com/list/co,c,2531190,000000,10,1.html" class="resume-href" target="_blank">前程无忧网</a></li>
                    <li class="submit-resume-li"><a href="http://company.zhaopin.com/_CC382743818.htm" class="resume-href" target="_blank">智联招聘网</a></li>
                    <li class="submit-resume-li"><a href="https://www.lagou.com/gongsi/j92449.html?schoolJob=true" class="resume-href" target="_blank">拉勾网</a></li>
                </ul>
            </div>
        </div>
        <!--来到瑞云这些全都有-end-->


    </div>
    <!--网站主体内容-中文-end-->

</div>


